[{"number": 53593, "title": "ValueError: node 'Placeholder' in input_map does not exist in graph (input_map entry: input_image:0->Placeholder:0)", "body": "### System information\r\n\r\n-   **Have I written custom code**:\r\n-   **OS Platform and Distribution (Windows 10)**:\r\n-   **TensorFlow installed from (binary)**:\r\n-   **TensorFlow version (1.15)**:\r\n-   **Python version(3.7.6)**:\r\n-   **CUDA/cuDNN version(10.0)**:\r\n-   **GPU model and memory(GTX 1660ti and 6GB)**:\r\n\r\n\r\n### Description of problem\r\nI was running file.py but still, it is not running, I did some changes in the source file. Still, the placeholder error is the same. The code is also updated with this question. Kindly review and Help.\r\n\r\n### Source code / logs\r\n\r\n#### minimal code\r\n    with tf.io.gfile.GFile(args.model, \"rb\") as f:\r\n        graph_def = tf.compat.v1.GraphDef()\r\n        graph_def.ParseFromString(f.read())\r\n    \r\n        with tf.Graph().as_default() as graph:\r\n            generated_image_1, generated_image_2, generated_image_3, = tf.import_graph_def(\r\n                    graph_def, \r\n                    input_map={'input_image' : input_tensor, 'short_edge_1' : short_edge_1, 'short_edge_2' : short_edge_2, 'short_edge_3' : short_edge_3}, \r\n                    return_elements=['style_subnet/conv-block/resize_conv_1/output:0', 'enhance_subnet/resize_conv_1/output:0', 'refine_subnet/resize_conv_1/output:0'], \r\n                    name=None, \r\n                    op_dict=None, \r\n                    producer_op_list=None  *#line number 55*\r\n                )\r\n    \r\n    short_edges = [int(e) for e in args.hierarchical_short_edges.split(',')]\r\n\r\n#### error\r\n\r\n```\r\n(myenv) D:\\subbu>python file.py --model=models/model.pb --input_image=test_images/image.jpg\r\n2021-12-25 00:54:11.765889: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll\r\ninput image -  test_images/image.jpg (1200, 630, 3)\r\nWARNING:tensorflow:From file.py:55: calling import_graph_def (from tensorflow.python.framework.importer) with op_dict is deprecated and will be removed in a future version.\r\nInstructions for updating:\r\nPlease file an issue at https://github.com/tensorflow/tensorflow/issues if you depend on this feature.\r\nTraceback (most recent call last):\r\n  File \"C:\\Users\\subbu\\myenv\\lib\\site-packages\\tensorflow_core\\python\\framework\\importer.py\", line 501, in _import_graph_def_internal\r\n    graph._c_graph, serialized, options)  # pylint: disable=protected-access\r\ntensorflow.python.framework.errors_impl.InvalidArgumentError: node 'Placeholder' in input_map does not exist in graph (input_map entry: input_image:0->Placeholder:0)\r\n\r\n\r\nDuring handling of the above exception, another exception occurred:\r\n\r\nTraceback (most recent call last):\r\n  File \"file.py\", line 87, in <module>\r\n    main()\r\n  File \"file.py\", line 55, in main\r\n    producer_op_list=None\r\n  File \"C:\\Users\\subbu\\myenv\\lib\\site-packages\\tensorflow_core\\python\\util\\deprecation.py\", line 507, in new_func\r\n    return func(*args, **kwargs)\r\n  File \"C:\\Users\\subbu\\myenv\\lib\\site-packages\\tensorflow_core\\python\\framework\\importer.py\", line 405, in import_graph_def\r\n    producer_op_list=producer_op_list)\r\n  File \"C:\\Users\\subbu\\myenv\\lib\\site-packages\\tensorflow_core\\python\\framework\\importer.py\", line 505, in _import_graph_def_internal\r\n    raise ValueError(str(e))\r\nValueError: node 'Placeholder' in input_map does not exist in graph (input_map entry: input_image:0->Placeholder:0)\r\n```", "comments": ["Hi @shubhambagwari ! \r\nIt seems you are using older versions(1.x versions) of Tensorflow which is not supported any more. Attaching relevant threads for reference. Ref [1](https://github.com/tensorflow/tensorflow/issues/18352), [2](https://forums.developer.nvidia.com/t/set-input-to-tensorflow-frozen-model-before-converting-to-trt-fails/110098).   Please upgrade your code  to 2.x versions and let us know!Thanks!", "I am using tensorflow 1.15 version\n\nGet Outlook for Android<https://aka.ms/AAb9ysg>\n________________________________\nFrom: mohantym ***@***.***>\nSent: Friday, December 31, 2021 6:14:09 PM\nTo: tensorflow/tensorflow ***@***.***>\nCc: Shubham Bagwari ***@***.***>; Mention ***@***.***>\nSubject: Re: [tensorflow/tensorflow] ValueError: node 'Placeholder' in input_map does not exist in graph (input_map entry: input_image:0->Placeholder:0) (Issue #53593)\n\n\nHi @shubhambagwari<https://github.com/shubhambagwari> !\nIt seems you are using older versions(1.x versions) of Tensorflow which is not supported any more. Attaching relevant threads for reference. Ref 1<https://github.com/tensorflow/tensorflow/issues/18352>, 2<https://forums.developer.nvidia.com/t/set-input-to-tensorflow-frozen-model-before-converting-to-trt-fails/110098>. Please upgrade your code to 2.x versions and let us know!Thanks!\n\n\u2014\nReply to this email directly, view it on GitHub<https://github.com/tensorflow/tensorflow/issues/53593#issuecomment-1003367927>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AGBQG4ESPCKLREYS7BRXJ3DUTWQRTANCNFSM5LA36P6Q>.\nYou are receiving this because you were mentioned.Message ID: ***@***.***>\n", "Hi @shubhambagwari Please post this on [Forum](https://discuss.tensorflow.org/) or Stackoverflow for further assistance ? Thanks!", "This issue has been automatically marked as stale because it has no recent activity. It will be closed if no further activity occurs. Thank you.\n", "Closing as stale. Please reopen if you'd like to work on this further.\n", "Are you satisfied with the resolution of your issue?\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53593\">Yes</a>\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53593\">No</a>\n"]}, {"number": 53592, "title": "update `is_numeric_tensor` with new dtypes", "body": "`tf.debugging.is_numeric_tensor` is out-of-date. Some new dtypes are not there.", "comments": []}, {"number": 53591, "title": "[TF:TRT] refactor einsum converter", "body": "This change moves the conversion function for the \"Einsum\" operation and all associated helper functions to a separate translation unit `tf2tensorrt/convert/ops/einsum.cc`. A small amount of refactoring is applied to eliminate functions which duplicate the functionality found in `TRTNetworkBuilder`. Functions which exceed a certain \"cognitive complexity\" calculated by clang are refactored to be below the threshold. Tests are updated to reflect the fact that certain error messages changed when updating the converter to use the `OpConverterBase` class.", "comments": ["Rebased on #53602, which should be merged shortly. Added 1 commit to use `DimsAdapter` to address comment.", "Can you squash the commits into one? thanks!", "squashed", "Would you please fix these errors:\r\n[third_party/tensorflow/compiler/tf2tensorrt/convert/ops/einsum.cc:15](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/tf2tensorrt/convert/ops/einsum.cc?l=15&ws=tap-prod-presubmit/170220345&snapshot=2):19: error: extra tokens at end of #ifdef directive [-Werror,-Wextra-tokens]\r\n#ifdef GOOGLE_CUDA&& GOOGLE_TENSORRT\r\n                  ^\r\n                  //\r\n[third_party/tensorflow/compiler/tf2tensorrt/convert/ops/einsum.cc:46](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/tf2tensorrt/convert/ops/einsum.cc?l=46&ws=tap-prod-presubmit/170220345&snapshot=2):13: error: unused variable 'n' [-Werror,-Wunused-variable]\r\n  const int n = values.size();\r\n            ^\r\n[third_party/tensorflow/compiler/tf2tensorrt/convert/ops/einsum.cc:681](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/tf2tensorrt/convert/ops/einsum.cc?l=681&ws=tap-prod-presubmit/170220345&snapshot=2):17: error: unused variable 'node_def' [-Werror,-Wunused-variable]", "> Would you please fix these errors: [third_party/tensorflow/compiler/tf2tensorrt/convert/ops/einsum.cc:15](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/tf2tensorrt/convert/ops/einsum.cc?l=15&ws=tap-prod-presubmit/170220345&snapshot=2):19: error: extra tokens at end of #ifdef directive [-Werror,-Wextra-tokens] #ifdef GOOGLE_CUDA&& GOOGLE_TENSORRT ^ // [third_party/tensorflow/compiler/tf2tensorrt/convert/ops/einsum.cc:46](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/tf2tensorrt/convert/ops/einsum.cc?l=46&ws=tap-prod-presubmit/170220345&snapshot=2):13: error: unused variable 'n' [-Werror,-Wunused-variable] const int n = values.size(); ^ [third_party/tensorflow/compiler/tf2tensorrt/convert/ops/einsum.cc:681](https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/compiler/tf2tensorrt/convert/ops/einsum.cc?l=681&ws=tap-prod-presubmit/170220345&snapshot=2):17: error: unused variable 'node_def' [-Werror,-Wunused-variable]\r\n\r\nThanks for letting me know, I'll take care of it", "Rebased and squashed the fixes for clang warnings.", "I guess I probably didn't fix the clang warning regarding the preprocessor. I didn't realize the issue is probably because of writing `#ifdef` instead of `#if` until you commented on my other PR. Let me know if you changed this on your end or if I need to push the change", "> I guess I probably didn't fix the clang warning regarding the preprocessor. I didn't realize the issue is probably because of writing `#ifdef` instead of `#if` until you commented on my other PR. Let me know if you changed this on your end or if I need to push the change\r\n\r\nWould you please fix that and squash?", "done"]}, {"number": 53590, "title": "TF > 2.5 does not work properly for keras.fit for dictionary inputs", "body": "<em>Please make sure that this is a bug. As per our\r\n[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),\r\nwe only address code/doc bugs, performance issues, feature requests and\r\nbuild/installation issues on GitHub. tag:bug_template</em>\r\n\r\n**System information**\r\n- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes\r\n- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04\r\n- TensorFlow installed from (source or binary): binary\r\n- TensorFlow version (use command below): 2.5.2, 2.6.2, 2.7\r\n- Python version: 3.9\r\n- CUDA/cuDNN version: 11.3\r\n- GPU model and memory: 1080 Ti\r\n\r\n\r\n**Describe the current behavior**\r\n\r\nIf I use TF 2.5.2 with keras.fit and inputs that are dictionaries for my multi input model, my model will fit.  If I used TF 2.6.* or 2.7.* I get out of memory errors.  \r\n\r\n**Describe the expected behavior**\r\n\r\nTF should not run out of memory in one version and not run out of memory in another, this model is definitively fittable with my GPU memory.\r\n\r\n**[Contributing](https://www.tensorflow.org/community/contribute)**\r\n\r\n- Do you want to contribute a PR? (yes/no): no\r\n- Briefly describe your candidate solution(if contributing):\r\n\r\nI did find a solution and that was to start using tf.dataset with from_generator being based on my input dictionaries instead of directly using dictionaries for my multi input model.  Why this would make any difference I do not know and this is the bug that should be addressed.\r\n\r\n**Standalone code to reproduce the issue**\r\n\r\nDon't have a standalone case, but this should be easily identifiable, there should be unit tests around all the different ways of passing input to keras.fit.\r\n\r\n**Other info / logs** Include any logs or source code that would be helpful to\r\ndiagnose the problem. If including tracebacks, please include the full\r\ntraceback. Large logs and files should be attached.\r\n", "comments": ["@jostheim \r\nIn order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!", "I won't be providing a code snippet, I am just reporting a bug, I found a work around so feel free to ignore the bug if you don't care.", "@jostheim Without the reproducible code, it would be difficult for us to debug the issue. If you're unable to provide the code could you please post in [TF discussion Forum](https://discuss.tensorflow.org/) and move this issue to closed status ?  Thank you!\r\n", "Up to you, I explained the issue, you can write unit tests for it, pass in data to keras.fit as a dictionary of numpy arrays for a reasonably large model (67E6 parameters) and it goes OOM, use a tf.dataset instead and it doesn't go OOM.  I have thousands of lines of code in my model and any dataset is gigabytes, I can't give you a simple example..", "Oh and by the by if anyone needs to convert multi-input dictionary to a dataset so it won't OOM error, here is my code.  Hope it helps someone!\r\n\r\n\r\n```\r\n       features_output_sig = {}\r\n        for i, (k, v) in enumerate(features.items()):\r\n            features_output_sig[k] = tf.TensorSpec(list(v[0].shape), dtype=tf.float32)\r\n        targets_output_sig = {}\r\n        for i, (k, v) in enumerate(features.items()):\r\n            targets_output_sig[k] = tf.TensorSpec(list(v[0].shape), dtype=tf.float32)\r\n\r\n        def train_generator():\r\n            size = list(features.values())[0].shape[0]\r\n            for j in range(size):\r\n                features_d = {}\r\n                for k, v in features.items():\r\n                    features_d[k] = v[j]\r\n                targets_d = {}\r\n                for k, v in targets.items():\r\n                    targets_d[k] = v[j]\r\n                yield features_d, targets_d\r\n\r\n        train_dataset = tf.data.Dataset.from_generator(train_generator, output_signature=(features_output_sig, targets_output_sig))\r\n\r\n\r\n```", "@jostheim Thank you for the update! \r\nPlease post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)\r\nTo know more see;\r\n[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)\r\nThank you!", "This issue has been automatically marked as stale because it has no recent activity. It will be closed if no further activity occurs. Thank you.\n", "Closing as stale. Please reopen if you'd like to work on this further.\n", "Are you satisfied with the resolution of your issue?\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53590\">Yes</a>\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53590\">No</a>\n"]}, {"number": 53589, "title": "Updating from the original ", "body": null, "comments": []}, {"number": 53588, "title": "Request for RandomIllumination layer in keras", "body": "Something like this already is possible with `ImageDataGenerator` but with corners in it (only applies brightness scale).\r\nWhat is needed is a full keras layer that randomize illumination differences spatially across the image (or even a single scaling factor to the whole image).\r\ni think more ideas can be added to something like this if it was implemented properly.", "comments": ["@MohamedAliRashad ,\r\nPlease post this issue on [keras-team/keras](https://github.com/keras-team/keras/issues) repo.\r\nTo know more refer to:\r\nhttps://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999\r\n", "This issue has been automatically marked as stale because it has no recent activity. It will be closed if no further activity occurs. Thank you.\n", "Closing as stale. Please reopen if you'd like to work on this further.\n"]}, {"number": 53587, "title": "PKIX path validation failed for giflib/giflib-5.2.1.tar.gz ( CertPathValidatorException )", "body": "<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>\r\n\r\n**System information**\r\n- OS Platform and Distribution: Linux Ubuntu 18\r\n- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:\r\n- TensorFlow installed from (source or binary): source\r\n- TensorFlow version: 2.7\r\n- Python version: 3.8.10\r\n- Installed using virtualenv? pip? conda?:  docker pull tensorflow/tensorflow:devel\r\n- Bazel version (if compiling from source): 3.7.2\r\n- GCC/Compiler version (if compiling from source): gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0\r\n- CUDA/cuDNN version: \r\n- GPU model and memory: \r\n\r\n\r\n\r\n**Describe the problem**\r\n\r\n**Reproduction step:**\r\n bazel build //tensorflow/tools/graph_transforms:transform_graph\r\n\r\n**ERROR:** tensorflow/tensorflow/core/platform/default/build_config/BUILD:172:11: //tensorflow/core/platform/default/build_config:gif depends on @gif//:gif in repository @gif which failed to fetch. no such package '@gif//': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz, https://pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz] to /root/.cache/bazel/_bazel_root/ce3ec9ad38e107ecc2ce5a4b33070bd2/external/gif/temp11457534064291798322/giflib-5.2.1.tar.gz: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed\r\nERROR: Analysis of target '//tensorflow/tools/graph_transforms:transform_graph' failed; build aborted: Analysis failed\r\n\r\n\r\n**Logs:**\r\n\r\nINFO: Found applicable config definition build:dynamic_kernels in file /local/mnt/workspace/sdks/tf_src/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS\r\nWARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/curl.haxx.se/download/curl-7.78.0.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\r\nINFO: Repository gif instantiated at:\r\n  /local/mnt/workspace/sdks/tf_src/tensorflow/WORKSPACE:15:14: in <toplevel>\r\n  /local/mnt/workspace/sdks/tf_src/tensorflow/tensorflow/workspace2.bzl:1089:21: in workspace\r\n  /local/mnt/workspace/sdks/tf_src/tensorflow/tensorflow/workspace2.bzl:366:20: in _tf_repositories\r\n  /local/mnt/workspace/sdks/tf_src/tensorflow/third_party/repo.bzl:113:21: in tf_http_archive\r\nRepository rule _tf_http_archive defined at:\r\n  /local/mnt/workspace/sdks/tf_src/tensorflow/third_party/repo.bzl:66:35: in <toplevel>\r\nWARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\r\nWARNING: Download from https://pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed\r\nERROR: An error occurred during the fetch of repository 'gif':\r\n   Traceback (most recent call last):\r\n        File \"/local/mnt/workspace/sdks/tf_src/tensorflow/third_party/repo.bzl\", line 53, column 33, in _tf_http_archive_impl\r\n                ctx.download_and_extract(\r\nError in download_and_extract: java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz, https://pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz] to /root/.cache/bazel/_bazel_root/ce3ec9ad38e107ecc2ce5a4b33070bd2/external/gif/temp11457534064291798322/giflib-5.2.1.tar.gz: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed\r\nINFO: Repository icu instantiated at:\r\n  /local/mnt/workspace/sdks/tf_src/tensorflow/WORKSPACE:15:14: in <toplevel>\r\n  /local/mnt/workspace/sdks/tf_src/tensorflow/tensorflow/workspace2.bzl:1082:28: in workspace\r\n  /local/mnt/workspace/sdks/tf_src/tensorflow/tensorflow/workspace2.bzl:70:8: in _initialize_third_party\r\n  /local/mnt/workspace/sdks/tf_src/tensorflow/third_party/icu/workspace.bzl:6:20: in repo\r\n  /local/mnt/workspace/sdks/tf_src/tensorflow/third_party/repo.bzl:113:21: in tf_http_archive\r\nRepository rule _tf_http_archive defined at:\r\n  /local/mnt/workspace/sdks/tf_src/tensorflow/third_party/repo.bzl:66:35: in <toplevel>\r\nERROR: /local/mnt/workspace/sdks/tf_src/tensorflow/tensorflow/core/platform/default/build_config/BUILD:172:11: //tensorflow/core/platform/default/build_config:gif depends on @gif//:gif in repository @gif which failed to fetch. no such package '@gif//': java.io.IOException: Error downloading [https://storage.googleapis.com/mirror.tensorflow.org/pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz, https://pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz] to /root/.cache/bazel/_bazel_root/ce3ec9ad38e107ecc2ce5a4b33070bd2/external/gif/temp11457534064291798322/giflib-5.2.1.tar.gz: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed\r\nERROR: Analysis of target '//tensorflow/tools/graph_transforms:transform_graph' failed; build aborted: Analysis failed\r\nINFO: Elapsed time: 40.378s\r\nINFO: 0 processes.\r\nFAILED: Build did NOT complete successfully (186 packages loaded, 8493 targets configured)\r\n", "comments": ["Hi @Saduf2019 ! Could you please look at this issue?", "@sdp009 \r\nApologies for the delayed response,is this still an issue", "@Saduf2019 , issue is still reproducible. I also tried with different machines. I think, something wrong with 'gif' repo keystore with importing SSL cert. I don't know much on this.\r\n\r\nWARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target\r\nWARNING: Download from https://pilotfiber.dl.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed\r\nERROR: An error occurred during the fetch of repository 'gif':\r\n   Traceback (most recent call last):\r\n        File \"/local/mnt/workspace/sdks/tf_src/tensorflow/third_party/repo.bzl\", line 53, column 33, in _tf_http_archive_impl\r\n                ctx.download_and_extract(\r\nError in download_and_extract: java.io.IOException", "Could you try the below and build again.\r\n```\r\napt-get update \r\napt-get install git\r\n```\r\n", "This issue has been automatically marked as stale because it has no recent activity. It will be closed if no further activity occurs. Thank you.\n", "Closing as stale. Please reopen if you'd like to work on this further.\n", "Are you satisfied with the resolution of your issue?\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53587\">Yes</a>\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53587\">No</a>\n"]}, {"number": 53586, "title": "TypeError: slice indices must be integers or None or have an __index__ method for @tf.function and when I use tfp.mcmc.NoUTurnSampler()", "body": "**System information**\r\n- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Big Sur\r\n- TensorFlow installed from (source or binary): using homebrew\r\n- TensorFlow version (use command below): tf-nightly==2.9.0.dev20211224\r\n- Tensorflow probability version: tensorflow-probability==0.13.0\r\n- Python version: Python 3.9.9\r\n\r\n\r\n**Describe the current behavior**\r\nI am unable to use @tf.function with indexing, for instance, the code below gives\r\n\r\n- Auscomp.Qobs is data\r\nt_end = len(Auscomp.Qobs)\r\nt_obs = np.linspace(start=0.,\r\n                    stop= t_end,\r\n                    num=int(t_end)).tolist()\r\nAuscomp.Prec.values is observed data values.\r\n\r\n@tf.function(jit_compile=True)\r\ndef p(t):\r\n    pos = tf.raw_ops.Bucketize(input=t,boundaries=t_obs)\r\n    precip_t = Auscomp.Prec.values[pos - 1:pos]\r\n\r\n    return precip_t[0]\r\n\r\n- call function\r\n\r\np(1.5) throws the error message \r\n\r\nTypeError: in user code:\r\n\r\n    File \"<ipython-input-3-f42dda5a54a8>\", line 20, in p  *\r\n        precip_t = Auscomp.Prec.values[pos - 1:pos]\r\n\r\n    TypeError: slice indices must be integers or None or have an __index__ method\r\n\r\n**Describe the expected behavior**\r\nI expect to have scaler value returned. For instance, if I add \r\ntf.config.run_functions_eagerly(True)  at the top of the programme the function works.\r\nBut I also have functions that solve ODEs and do Bayesian inference with TensorFlow probability. So when I run a function tfp.mcmc.NoUTurnSampler() that calls an ODE that calls the above function, I get the  message below\r\n\r\nWARNING:tensorflow:It looks like tf.function behavior was disabled, perhaps using tf.config.run_functions_eagerly. Vectorization primitives (e.g. tf.vectorized_map) require tf.function to work. These primitives will override the disable.\r\n\r\nand later the error\r\n\r\nFile \"<ipython-input-6-7453b3323d01>\", line 27, in precip\r\n        precip_t = Auscomp.Prec.values[pos - 1:pos]\r\n\r\n    TypeError: slice indices must be integers or None or have an __index__ method\r\n\r\n**Standalone code to reproduce the issue**\r\n\r\nimport numpy as np\r\nimport tensorflow as tf\r\nimport tensorflow_probability as tfp\r\n\r\n\r\nt_end = 21\r\nt_obs = np.linspace(0.0, t_end, 20)\r\n\r\n- data set with zeros and ones \r\nprecip = np.zeros(t_end + 1)\r\nt_precip = np.linspace(0, t_end + 1, num=t_end + 2).tolist()\r\n\r\nprecip[0::7] = 1.0\r\n\r\n@tf.function\r\ndef p(t):\r\n        pos = tf.raw_ops.Bucketize(input=t,boundaries=t_precip)\r\n    \r\n        precip_t = precip[pos - 1:pos]\r\n\r\n        return precip_t[0]\r\n- call function  \r\np(1.5)\r\n", "comments": ["@DamingoNdiwa \r\nIn order to expedite the trouble-shooting process, please provide a complete code snippet to reproduce the issue reported here. Thanks!", "@sushreebarsa \r\nthank you, here is the link to a Google Colab that has comments and some data with explanations.\r\nhttps://colab.research.google.com/drive/1DU7gsLW2UkUJGjE6L5erWVZW2vljtN6-?usp=sharing", "@Saduf2019  Was able to reproduce the issue in TF [v2.7.0](https://colab.research.google.com/gist/sushreebarsa/d1bef46615f7b88391e3e9d5c0869c84/hbvode.ipynb#scrollTo=TyrCGbsR8hA-) and [tf-nightly](https://colab.research.google.com/gist/sushreebarsa/7df0a83cbc8045e6616865bd13fee5af/hbvode.ipynb#scrollTo=JOP_kD3K-zXa) (2.9.0-dev20220106),please find the attached gists for reference.Thanks!", "@DamingoNdiwa \r\nPlease refer to similar error issues and let us know:\r\n[link](https://stackoverflow.com/questions/28272322/typeerror-slice-indices-must-be-integers-or-none-or-have-an-index-method/28272778), [link1](https://careerkarma.com/blog/python-typeerror-slice-indices-must-be-integers-or-none/), [link2](https://www.stechies.com/typeerror-slice-indices-must-integers-none-have-index-metho/)", "@Saduf2019 Thanks, I have tried similar solutions. I think the problem is the autograph used by  @tf.function. I now use a different package for this.", "@DamingoNdiwa \r\nPlease move this to closed status, as it is not an issue any more.", "Yes, I will close it. I left thinking it could be resolved because only TensorFlow 2. Thank you.", "Are you satisfied with the resolution of your issue?\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53586\">Yes</a>\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53586\">No</a>\n"]}, {"number": 53585, "title": "Inconsistent results of K.dot", "body": "there are two numpy matrixs\uff1a\r\n**first** with shape:[1,39],dtype=float32, \r\n **second** with shape[39,2],dtype=float32\r\n\r\n`\r\nimport tensorflow.keras.backend as K\r\n`\r\n`\r\nK.dot(tf.constant(first),tf.constant(second[:,0:1]))\r\n`\r\nOut[5]: <tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[**0.8299226**]], dtype=float32)>\r\n\r\n``\r\nK.dot(tf.constant(first),tf.constant(second[:,0:2]))\r\n``\r\nOut[6]: <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[**0.8301826**, 1.0395387]], dtype=float32)>\r\n\r\nthe two results diff 2.66e-4 which is big enough for me\r\n\r\n**can anybody tell me why this happens and any solutions?** \r\n\r\ntf v2.4.0\r\n\r\nvalues of the matrix:\r\n\r\nfirst\r\nOut[7]: \r\narray([[-7.2378081e-01,  1.6171148e+00, -1.4751177e+00, -1.1468199e+00,\r\n        -9.4957459e-01, -1.1004009e+00, -6.0811418e-01,  1.3347808e+00,\r\n        -5.6221259e-01, -2.8636627e-02, -1.3238943e+00,  1.3290122e+00,\r\n         3.3704469e-01,  4.8254672e-01, -6.0419792e-01,  7.0332962e-01,\r\n        -8.1343579e-01, -1.7627051e+00,  3.5882825e-01, -1.4614569e+00,\r\n        -3.9931360e-01, -9.7357178e-01, -6.1273777e-01,  4.6369970e-01,\r\n         9.3952209e-01,  5.2290356e-01, -6.9766754e-01,  4.8909006e-01,\r\n        -2.4669762e-01,  1.1569391e+00,  8.5423976e-01, -1.2952095e-03,\r\n        -3.4862864e-01, -2.7243546e-01,  8.0830842e-01, -3.0422598e-01,\r\n         2.8226626e-01, -5.6840044e-02, -7.3323792e-01]], dtype=float32)\r\n\r\nsecond[:,0:2]\r\nOut[8]: \r\narray([[-0.09545885,  0.0301608 ],\r\n       [ 0.10142329, -0.09098691],\r\n       [-0.04838413,  0.15964064],\r\n       [ 0.16257629, -0.1777806 ],\r\n       [-0.131538  , -0.14655067],\r\n       [-0.085496  , -0.13280763],\r\n       [ 0.18278474, -0.11492068],\r\n       [ 0.03820068,  0.00508413],\r\n       [-0.00234684, -0.10233091],\r\n       [ 0.12245703,  0.10799986],\r\n       [ 0.01588374,  0.05467606],\r\n       [-0.15388036,  0.14180547],\r\n       [-0.0121727 , -0.08367829],\r\n       [ 0.09906906,  0.09994766],\r\n       [-0.07855757, -0.18606487],\r\n       [-0.02123192,  0.07851872],\r\n       [-0.1276356 , -0.12484328],\r\n       [-0.17431177,  0.00072895],\r\n       [-0.02924933, -0.01532622],\r\n       [ 0.06264558, -0.19014324],\r\n       [ 0.07497945, -0.0103462 ],\r\n       [ 0.00148363,  0.12542334],\r\n       [ 0.0202539 , -0.04290475],\r\n       [ 0.06409332,  0.17675939],\r\n       [ 0.07451543, -0.01164982],\r\n       [ 0.14731088, -0.16865423],\r\n       [-0.13444461, -0.14083615],\r\n       [ 0.17176068, -0.09960409],\r\n       [-0.12674293, -0.17646563],\r\n       [ 0.13016194,  0.09005257],\r\n       [-0.19060531, -0.06375018],\r\n       [ 0.03746909,  0.00599393],\r\n       [ 0.18026543,  0.18963405],\r\n       [-0.11866984, -0.11520495],\r\n       [ 0.09463558,  0.11655363],\r\n       [ 0.05268271, -0.1161972 ],\r\n       [-0.1774411 ,  0.18842372],\r\n       [ 0.02491291,  0.12098533],\r\n       [-0.11909473,  0.03792849]], dtype=float32)", "comments": ["@davy868 ,\r\nIn order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.Also please try to test the code in latest stable tf v2.7.It helps.Thanks!", "![image](https://user-images.githubusercontent.com/42214343/147809461-e7e2bf7f-01e0-46d5-8593-64c90f668e19.png)\r\n@tilakrayal ", "@davy868 ,\r\nI ran the code shared and face a different error, please find the gist [here](https://colab.research.google.com/gist/tilakrayal/534bf8de81ba1724d6a00f9f3179c9d1/untitled173.ipynb) and share all dependencies to replicate the issue or share a colab gist with the reported error.\r\n\r\n\r\n", "This issue has been automatically marked as stale because it has no recent activity. It will be closed if no further activity occurs. Thank you.\n", "Can you please look at this link [1](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dot) and [2](https://keras.io/api/layers/merging_layers/dot/) for more information on tf.keras.layers.Dot.It  helps.Thanks", "Closing as stale. Please reopen if you'd like to work on this further.\n", "Are you satisfied with the resolution of your issue?\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53585\">Yes</a>\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53585\">No</a>\n"]}, {"number": 53583, "title": "Release tensorflow-macos wheel compatible with Python 3.9 and x86", "body": "Currently in version 2.7.0 of `tensorflow-macos`, there are only 3 wheels released in pip: 2 for arm64 supporting Python 3.8-3.9 and 1 for x86 only supporting Python 3.8.\r\nIt would be great to have also a wheel for Python 3.9 for the x86 architecture.\r\nThe same thing also applies for `tensorflow-metal`.\r\n\r\n\r\n**System information**\r\n- TensorFlow version (you are using): 2.7.0\r\n\r\n\r\n\r\n**Describe the feature and the current behavior/state.**\r\nSee above\r\n\r\n**Will this change the current api? How?**\r\nNo\r\n\r\n**Who will benefit with this feature?**\r\nEvery Intel Mac User with Python 3.9\r\n\r\n**Any Other info.**\r\n", "comments": ["There are several confusions here.\r\n\r\n1. `tensorflow_macos` is intended to work for Apple M1 devices and only those. That is, only for ARM architectures, not x86.\r\n2. `tensorflow_macos` is not released by Google, it is a community build done by people at Apple\r\n3. `tensorflow` is the wheel to use for x86.", "Are you satisfied with the resolution of your issue?\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53583\">Yes</a>\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53583\">No</a>\n", "Thanks @mihaimaruseac for resolving my confusion. Sorry about that. So then I will ask Apple about `tensorflow-metal` for Python 3.9.", "Just in case you're like me and find this issue looking for why `tensorflow_macos` does not have an Intel Mac binary wheel package for Python 3.9 (cp39 x86_64), but want a clear(er) resolution method\u2026\r\n\r\nYou'll want something like this in your `pyproject.toml` for Poetry, or its equivalent in a `requirements.txt`:\r\n\r\n```toml\r\n[tool.poetry.dependencies.tensorflow]\r\nversion = \"2.8.0\"\r\nmarkers = \"sys_platform != 'darwin' or (sys_platform == 'darwin' and platform_machine != 'arm64') \"\r\n\r\n[tool.poetry.dependencies.tensorflow_macos]\r\nversion = \"2.8.0\"\r\nmarkers = \"sys_platform == 'darwin' and platform_machine == 'arm64'\"\r\n```\r\n\r\nThere is a Python 3.8 Intel binary wheel package (cp38) for `tensorflow_macos` but per [this comment](https://github.com/tensorflow/tensorflow/issues/53583#issuecomment-1025017751), it shouldn't be used.\r\n\r\nThis configuration was tested on a 2022 M1 with macOS 12.2 and a 2018 MBP with macOS 11.6.\r\n\r\n_Maximizing for some SEO with word selection because it took me about 10 minutes to find this, so putting  terms I searched for in it\u2026_"]}, {"number": 53580, "title": "Update the release note ", "body": "Include details on Pluggable Profiler support and TensorFlow-oneDNN's discontinuation of explicit block tensor format support.", "comments": []}, {"number": 53579, "title": "AttributeError: 'NoneType' object has no attribute 'outer_context' when building a token classification model", "body": "Hi, I am training a token-classification model, and I use ELMO embeddings as one layer of my model.\r\n\r\nI'm using elmo embeddings from tensorflow hub, and I am using them with tensorflow 2.4.1. The same model architecture worked when built in Tensorflow 1.x, but I need to migrate it to TF2. I followed the instructions on how to replace hub.Module() with hub.KerasLayer() or hub.load() in order to use elmo in TF2. The example is with hub.load(). When using hub.KerasLayer() I cannot use the \"token\" signature. \r\n\r\nPlease note that the same model architecture worked in TF1, but I need a solution to make it work in TF2. \r\n\r\nThis is how I'm building the model: \r\n```\r\ndef ElmoEmbedding(x):\r\n    return elmo_model.signatures[\"tokens\"](tokens = tf.squeeze(tf.cast(x, tf.string)), sequence_len = tf.constant(batch_size * [max_len]))[\"elmo\"]\r\n\r\ndef build_model(max_len, n_words, n_tags): \r\n    word_input_layer = Input(shape=(max_len, 40, ))\r\n    elmo_input_layer = Input(shape=(max_len,), dtype=tf.string)\r\n    word_output_layer = Dense(n_tags, activation = 'softmax')(word_input_layer)\r\n    elmo_output_layer = Lambda(ElmoEmbedding, output_shape=(None, 1024))(elmo_input_layer)\r\n\r\n    output_layer = Concatenate()([word_output_layer, elmo_output_layer])\r\n    output_layer = BatchNormalization()(output_layer)\r\n    output_layer = Bidirectional(LSTM(units=512, return_sequences=True, recurrent_dropout=0.2, dropout=0.2))(output_layer)\r\n    output_layer = TimeDistributed(Dense(n_tags, activation='softmax'))(output_layer)\r\n    \r\n    model = Model([elmo_input_layer, word_input_layer], output_layer)\r\n    \r\n    return model\r\n```\r\n\r\nAnd therefore want to train the model as follows:\r\n```\r\nelmo_model = hub.load('https://tfhub.dev/google/elmo/3')\r\nmodel = build_model(max_len, n_words, n_tags)\r\nmodel.compile(optimizer=\"adam\", loss=\"sparse_categorical_crossentropy\", metrics=[\"accuracy\"])\r\nmodel.summary()\r\n\r\nhistory = model.fit([np.array(X1_train), np.array(X2_train).reshape((len(X2_train), max_len, 40))], \r\n                    y_train, \r\n                    validation_data=([np.array(X1_valid), np.array(X2_valid).reshape((len(X2_valid), max_len, 40))], y_valid),\r\n                    batch_size=32, epochs=2, verbose=1)\r\n```\r\n\r\nTo clarify, X1_train is a list of tokenized sentences and X2_train is a list of hand-picked features for every token in every sentence. \r\n\r\n\r\nThe error that I'm getting when calling model.fit is the following one:\r\n\r\n```\r\n---------------------------------------------------------------------------\r\nAttributeError                            Traceback (most recent call last)\r\n<ipython-input-14-04a3722fa4b2> in <module>\r\n     51                     y_train,\r\n     52                     validation_data=([np.array(X1_valid), np.array(X2_valid).reshape((len(X2_valid), max_len, 40))], y_valid),\r\n---> 53                     batch_size=32, epochs=2, verbose=1)\r\n     54 hist = pd.DataFrame(history.history)\r\n\r\n/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)\r\n   1098                 _r=1):\r\n   1099               callbacks.on_train_batch_begin(step)\r\n-> 1100               tmp_logs = self.train_function(iterator)\r\n   1101               if data_handler.should_sync:\r\n   1102                 context.async_wait()\r\n\r\n/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)\r\n    826     tracing_count = self.experimental_get_tracing_count()\r\n    827     with trace.Trace(self._name) as tm:\r\n--> 828       result = self._call(*args, **kwds)\r\n    829       compiler = \"xla\" if self._experimental_compile else \"nonXla\"\r\n    830       new_tracing_count = self.experimental_get_tracing_count()\r\n\r\n/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)\r\n    869       # This is the first call of __call__, so we have to initialize.\r\n    870       initializers = []\r\n--> 871       self._initialize(args, kwds, add_initializers_to=initializers)\r\n    872     finally:\r\n    873       # At this point we know that the initialization is complete (or less\r\n\r\n/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)\r\n    724     self._concrete_stateful_fn = (\r\n    725         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\r\n--> 726             *args, **kwds))\r\n    727 \r\n    728     def invalid_creator_scope(*unused_args, **unused_kwds):\r\n\r\n/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)\r\n   2967       args, kwargs = None, None\r\n   2968     with self._lock:\r\n-> 2969       graph_function, _ = self._maybe_define_function(args, kwargs)\r\n   2970     return graph_function\r\n   2971 \r\n\r\n/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)\r\n   3359 \r\n   3360           self._function_cache.missed.add(call_context_key)\r\n-> 3361           graph_function = self._create_graph_function(args, kwargs)\r\n   3362           self._function_cache.primary[cache_key] = graph_function\r\n   3363 \r\n\r\n/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)\r\n   3204             arg_names=arg_names,\r\n   3205             override_flat_arg_shapes=override_flat_arg_shapes,\r\n-> 3206             capture_by_value=self._capture_by_value),\r\n   3207         self._function_attributes,\r\n   3208         function_spec=self.function_spec,\r\n\r\n/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)\r\n    988         _, original_func = tf_decorator.unwrap(python_func)\r\n    989 \r\n--> 990       func_outputs = python_func(*func_args, **func_kwargs)\r\n    991 \r\n    992       # invariant: `func_outputs` contains only Tensors, CompositeTensors,\r\n\r\n/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)\r\n    632             xla_context.Exit()\r\n    633         else:\r\n--> 634           out = weak_wrapped_fn().__wrapped__(*args, **kwds)\r\n    635         return out\r\n    636 \r\n\r\n/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)\r\n    975           except Exception as e:  # pylint:disable=broad-except\r\n    976             if hasattr(e, \"ag_error_metadata\"):\r\n--> 977               raise e.ag_error_metadata.to_exception(e)\r\n    978             else:\r\n    979               raise\r\n\r\nAttributeError: in user code:\r\n\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:805 train_function  *\r\n        return step_function(self, iterator)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:795 step_function  **\r\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:1259 run\r\n        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica\r\n        return self._call_for_each_replica(fn, args, kwargs)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica\r\n        return fn(*args, **kwargs)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:788 run_step  **\r\n        outputs = model.train_step(data)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:754 train_step\r\n        y_pred = self(x, training=True)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:1012 __call__\r\n        outputs = call_fn(inputs, *args, **kwargs)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py:425 call\r\n        inputs, training=training, mask=mask)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py:560 _run_internal_graph\r\n        outputs = node.layer(*args, **kwargs)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:1012 __call__\r\n        outputs = call_fn(inputs, *args, **kwargs)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py:917 call\r\n        result = self.function(inputs, **kwargs)\r\n    <ipython-input-7-21ffba0b5a13>:7 ElmoEmbedding\r\n        return elmo_model.signatures[\"tokens\"](tokens = tf.squeeze(tf.cast(x, tf.string)), sequence_len = tf.constant(batch_size * [max_len]))[\"elmo\"]\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py:1669 __call__\r\n        return self._call_impl(args, kwargs)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/wrap_function.py:247 _call_impl\r\n        args, kwargs, cancellation_manager)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py:1687 _call_impl\r\n        return self._call_with_flat_signature(args, kwargs, cancellation_manager)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py:1736 _call_with_flat_signature\r\n        return self._call_flat(args, self.captured_inputs, cancellation_manager)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py:1924 _call_flat\r\n        forward_function, args_with_tangents = forward_backward.forward()\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py:1448 forward\r\n        self._inference_args, self._input_tangents)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py:1207 forward\r\n        self._forward_and_backward_functions(inference_args, input_tangents))\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py:1407 _forward_and_backward_functions\r\n        outputs, inference_args, input_tangents)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py:910 _build_functions_for_outputs\r\n        src_graph=self._func_graph)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/gradients_util.py:552 _GradientsHelper\r\n        to_ops, from_ops, colocate_gradients_with_ops, func_graphs, xs_set)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/gradients_util.py:125 _PendingCount\r\n        between_op_list, between_ops, colocate_gradients_with_ops)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_state.py:780 MaybeCreateControlFlowState\r\n        loop_state.AddWhileContext(op, between_op_list, between_ops)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_state.py:577 AddWhileContext\r\n        outer_forward_ctxt = forward_ctxt.outer_context\r\n\r\n    AttributeError: 'NoneType' object has no attribute 'outer_context'\r\n```\r\n\r\nAny tips would help!", "comments": ["@popkristina Could you please try to upgrade to latest TensorFlow version 2.7.0 and let us know the outcome?Thanks!", "> @popkristina Could you please try to upgrade to latest TensorFlow version 2.7.0 and let us know the outcome?Thanks!\r\n\r\nI did and I received the following error: \r\n\r\n```\r\n---------------------------------------------------------------------------\r\nAttributeError                            Traceback (most recent call last)\r\n<ipython-input-21-7173cff2a6ea> in <module>\r\n     55                     y_train,\r\n     56                     validation_data=([np.array(X1_valid), np.array(X2_valid).reshape((len(X2_valid), max_len, 40))], y_valid),\r\n---> 57                     batch_size=32, epochs=2, verbose=1)\r\n     58 hist = pd.DataFrame(history.history)\r\n\r\n/opt/conda/lib/python3.7/site-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)\r\n     65     except Exception as e:  # pylint: disable=broad-except\r\n     66       filtered_tb = _process_traceback_frames(e.__traceback__)\r\n---> 67       raise e.with_traceback(filtered_tb) from None\r\n     68     finally:\r\n     69       del filtered_tb\r\n\r\n/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py in autograph_handler(*args, **kwargs)\r\n   1127           except Exception as e:  # pylint:disable=broad-except\r\n   1128             if hasattr(e, \"ag_error_metadata\"):\r\n-> 1129               raise e.ag_error_metadata.to_exception(e)\r\n   1130             else:\r\n   1131               raise\r\n\r\nAttributeError: in user code:\r\n\r\n    File \"/opt/conda/lib/python3.7/site-packages/keras/engine/training.py\", line 878, in train_function  *\r\n        return step_function(self, iterator)\r\n    File \"/opt/conda/lib/python3.7/site-packages/keras/engine/training.py\", line 867, in step_function  **\r\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\r\n    File \"/opt/conda/lib/python3.7/site-packages/keras/engine/training.py\", line 860, in run_step  **\r\n        outputs = model.train_step(data)\r\n    File \"/opt/conda/lib/python3.7/site-packages/keras/engine/training.py\", line 808, in train_step\r\n        y_pred = self(x, training=True)\r\n    File \"/opt/conda/lib/python3.7/site-packages/keras/utils/traceback_utils.py\", line 67, in error_handler\r\n        raise e.with_traceback(filtered_tb) from None\r\n    File \"<ipython-input-15-adbacb2acf37>\", line 8, in ElmoEmbedding\r\n        return elmo_model.signatures[\"tokens\"](tokens = tf.squeeze(tf.cast(x, tf.string)), sequence_len = tf.constant(batch_size * [max_len]))[\"elmo\"]\r\n\r\n    AttributeError: Exception encountered when calling layer \"lambda_2\" (type Lambda).\r\n    \r\n    'NoneType' object has no attribute 'outer_context'\r\n    \r\n    Call arguments received:\r\n      \u2022 inputs=tf.Tensor(shape=(32, 300), dtype=string)\r\n      \u2022 mask=None\r\n      \u2022 training=True\r\n```\r\n\r\n Is it possible that I can't train a model with ELMO layer in TF 2 at all?", "@popkristina \r\nIn order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!", "> @popkristina In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!\r\n\r\nHere's a short kaggle kernel to reproduce the error:\r\n\r\nhttps://www.kaggle.com/popkristina/lstm-elmo?scriptVersionId=84384455\r\n\r\n", "@popkristina \r\nPlease post this issue on[ hub repo](https://github.com/tensorflow/hub/issues) to get the right help there?\r\nThank you!", "> @popkristina Please post this issue on[ hub repo](https://github.com/tensorflow/hub/issues) to get the right help there? Thank you!\r\n\r\nAlright, thank you.", "Hi Kristina,\r\n\r\nHope you are doing well!\r\n\r\nIs this issue resolved? I ma facing the same error.\r\n\r\nCould you please help me with the solution?\r\n\r\nThanks\r\nShakti", "\r\n\r\n\r\n> Hi Kristina,\r\n> \r\n> Hope you are doing well!\r\n> \r\n> Is this issue resolved? I ma facing the same error.\r\n> \r\n> Could you please help me with the solution?\r\n> \r\n> Thanks Shakti\r\n\r\nUnfortunately not. Apparently the way I tried to use my ELMO model with hub.load(..) is not supported in TF2. So instead I adapted my solution to TF1 where I can use hub.Module(..). The answer I got is here:  (https://github.com/tensorflow/hub/issues/838).\r\n\r\nHope this helps. Good luck!\r\n"]}, {"number": 53578, "title": "Failed to compile TensorFlow C++ API with Bazel and GCC 9.3 on WSL Ubuntu 20.04", "body": "Hi All,\r\n\r\n**System information**\r\n- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.3\r\n- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No\r\n- TensorFlow installed from (source or binary): TensorFlow GitHub branch r2.6\r\n- TensorFlow version: 2.6\r\n- Python version: 3.9.0\r\n- Installed using virtualenv? pip? conda?: conda's standard environment\r\n- Bazel version (if compiling from source): 3.7.2\r\n- GCC/Compiler version (if compiling from source): 9.3.0\r\n- CUDA/cuDNN version: No\r\n- GPU model and memory: No\r\n\r\n**Describe the problem**\r\n---\r\n\r\nI've been trying to compile TF C++ API from source using bazel and gcc on WSL Ubuntu 20.04 - AMD Ryzen 5 3600 - 12 cores with 12 GB of memory.\r\n\r\n**Command I used to compile**\r\n```\r\ncd tensorflow/\r\ngit branch r2.6\r\n./configure\r\nbazel build --cxxopt=\"-D_GLIBCXX_USE_CXX11_ABI=0\" --copt=\"-O3\" -c opt \\\r\n    --copt=-mavx --copt=-mavx2 --copt=-mfma --copt=-msse4.1  \\\r\n    --copt=-msse4.2 --copt=-mfpmath=both --config=nogcp --config=nonccl \\\r\n    //tensorflow:libtensorflow_cc.so\r\n```\r\n\r\n**Compile log and error message**\r\n```\r\nINFO: Options provided by the client:\r\n  Inherited 'common' options: --isatty=1 --terminal_columns=167\r\nINFO: Reading rc options for 'build' from /home/rangsiman/tensorflow/.bazelrc:\r\n  Inherited 'common' options: --experimental_repo_remote_exec\r\nINFO: Reading rc options for 'build' from /home/rangsiman/tensorflow/.bazelrc:\r\n  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true\r\nINFO: Reading rc options for 'build' from /home/rangsiman/tensorflow/.tf_configure.bazelrc:\r\n  'build' options: --action_env PYTHON_BIN_PATH=/home/rangsiman/miniconda3/envs/tf_cc/bin/python3 --action_env PYTHON_LIB_PATH=/home/rangsiman/miniconda3/envs/tf_cc/lib/python3.9/site-packages --python_path=/home/rangsiman/miniconda3/envs/tf_cc/bin/python3\r\nINFO: Found applicable config definition build:short_logs in file /home/rangsiman/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING\r\nINFO: Found applicable config definition build:v2 in file /home/rangsiman/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1\r\nINFO: Found applicable config definition build:nogcp in file /home/rangsiman/tensorflow/.bazelrc: --define=no_gcp_support=true\r\nINFO: Found applicable config definition build:nonccl in file /home/rangsiman/tensorflow/.bazelrc: --define=no_nccl_support=true\r\nINFO: Found applicable config definition build:linux in file /home/rangsiman/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels --distinct_host_configuration=false\r\nINFO: Found applicable config definition build:dynamic_kernels in file /home/rangsiman/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS\r\nDEBUG: /home/rangsiman/.cache/bazel/_bazel_rangsiman/941ebeb4a3431ad9648cd9d348263c60/external/tf_runtime/third_party/cuda/dependencies.bzl:51:10: The following command will download NVIDIA proprietary software. By using the software you agree to comply with the terms of the license agreement that accompanies the software. If you do not agree to the terms of the license agreement, do not use the software.\r\nINFO: Build options --action_env and --define have changed, discarding analysis cache.\r\nDEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = \"1556410077 -0400\"\r\nDEBUG: Repository io_bazel_rules_docker instantiated at:\r\n  /home/rangsiman/tensorflow/WORKSPACE:23:14: in <toplevel>\r\n  /home/rangsiman/tensorflow/tensorflow/workspace0.bzl:108:34: in workspace\r\n  /home/rangsiman/.cache/bazel/_bazel_rangsiman/941ebeb4a3431ad9648cd9d348263c60/external/bazel_toolchains/repositories/repositories.bzl:37:23: in repositories\r\nRepository rule git_repository defined at:\r\n  /home/rangsiman/.cache/bazel/_bazel_rangsiman/941ebeb4a3431ad9648cd9d348263c60/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>\r\nINFO: Analyzed target //tensorflow:libtensorflow_cc.so (212 packages loaded, 19185 targets configured).\r\nINFO: Found 1 target...\r\nERROR: /home/rangsiman/tensorflow/tensorflow/core/kernels/BUILD:3345:18: C++ compilation of rule '//tensorflow/core/kernels:matmul_op' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 134 argument(s) skipped)\r\ngcc: fatal error: Killed signal terminated program cc1plus\r\ncompilation terminated.\r\nTarget //tensorflow:libtensorflow_cc.so failed to build\r\nUse --verbose_failures to see the command lines of failed build steps.\r\nINFO: Elapsed time: 2600.294s, Critical Path: 791.86s\r\nINFO: 4437 processes: 416 internal, 4021 local.\r\nFAILED: Build did NOT complete successfully\r\n```\r\n\r\nI had run the same bazel build commands many times and I found that the compilations failed at different .cc files. So I was not sure if it was because the memory is not enough or not. I also tried `--jobs=8` and `--jobs=4` to limit the memory consumption but it didn't help. Any ideas to solve this issue? Thanks\r\n", "comments": ["I tried `--jobs=2` and it worked! So it's all about memory.", "Are you satisfied with the resolution of your issue?\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53578\">Yes</a>\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53578\">No</a>\n"]}, {"number": 53577, "title": "model.fit excess memory usage with GPU", "body": "I am running 4 scripts which should be equivalent in theory. However, two of those [which use GPU to train the model] are using 10 times more memory than their CPU counterparts. \r\n\r\nThe scripts which are using acceptable levels of memory are scripts 1 and 3. The unacceptable levels are scripts 2 and 4. \r\n\r\nHere is the code:\r\nscript1: https://pastebin.com/2gRbjKmx\r\nscript2: https://pastebin.com/GK9iE2DC\r\nscript3: https://pastebin.com/cUniWZxj\r\nscript4: https://pastebin.com/BwkWbHjg\r\n\r\nMy python version is 3.9.7 and tensorflow version is 2.4.1.\r\n\r\nThe OS is: Red Hat Enterprise Linux\r\nThe Kernel is: Linux 3.10.0-1160.2.1.el7.x86_64\r\nThe architecture is: x86-64\r\n\r\nThe GPU is Nvidia either P100 or Nvidia V100.", "comments": ["Hi @Chaudry24 ! I tried switching between CPU and GPU using tf.device() and checked the memory usage using memory_usage api. Memory usage in GPU was exceeding CPU memory usage  as you pointed out . Attaching [Gist ](https://colab.sandbox.google.com/gist/mohantym/e8a26e8b9928bd24c436c654ef8e8c4d/github_53577.ipynb#scrollTo=TLi1gNCx3H8v)for reference. \r\n\r\nPlease post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)\r\nTo know more see;\r\n[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) . Thanks!", "Hi @mohantym ! Thank you for taking the time and responding with these useful links. Here is the [link](https://github.com/keras-team/keras/issues/15843) to the issue I opened up. Thanks again!"]}, {"number": 53575, "title": "AttributeError: 'NoneType' object has no attribute 'outer_context' when building a token classification model", "body": "Hi, I am training a token-classification model, and I use ELMO embeddings as one layer of my model.\r\n\r\nI'm using elmo embeddings from tensorflow hub, and I am using them with tensorflow 2.4.1. The same model architecture worked when built in Tensorflow 1.x, but I need to migrate it to TF2. I followed the instructions on how to replace hub.Module() with hub.KerasLayer() or hub.load() in order to use elmo in TF2. The example is with hub.load(). When using hub.KerasLayer() I cannot use the \"token\" signature. \r\n\r\nPlease note that the same model architecture worked in TF1, but I need a solution to make it work in TF2. \r\n\r\nThis is how I'm building the model: \r\n```\r\ndef ElmoEmbedding(x):\r\n    return elmo_model.signatures[\"tokens\"](tokens = tf.squeeze(tf.cast(x, tf.string)), sequence_len = tf.constant(batch_size * [max_len]))[\"elmo\"]\r\n\r\ndef build_model(max_len, n_words, n_tags): \r\n    word_input_layer = Input(shape=(max_len, 40, ))\r\n    elmo_input_layer = Input(shape=(max_len,), dtype=tf.string)\r\n    word_output_layer = Dense(n_tags, activation = 'softmax')(word_input_layer)\r\n    elmo_output_layer = Lambda(ElmoEmbedding, output_shape=(None, 1024))(elmo_input_layer)\r\n\r\n    output_layer = Concatenate()([word_output_layer, elmo_output_layer])\r\n    output_layer = BatchNormalization()(output_layer)\r\n    output_layer = Bidirectional(LSTM(units=512, return_sequences=True, recurrent_dropout=0.2, dropout=0.2))(output_layer)\r\n    output_layer = TimeDistributed(Dense(n_tags, activation='softmax'))(output_layer)\r\n    \r\n    model = Model([elmo_input_layer, word_input_layer], output_layer)\r\n    \r\n    return model\r\n```\r\n\r\nAnd therefore want to train the model as follows:\r\n```\r\nelmo_model = hub.load('https://tfhub.dev/google/elmo/3')\r\nmodel = build_model(max_len, n_words, n_tags)\r\nmodel.compile(optimizer=\"adam\", loss=\"sparse_categorical_crossentropy\", metrics=[\"accuracy\"])\r\nmodel.summary()\r\n\r\nhistory = model.fit([np.array(X1_train), np.array(X2_train).reshape((len(X2_train), max_len, 40))], \r\n                    y_train, \r\n                    validation_data=([np.array(X1_valid), np.array(X2_valid).reshape((len(X2_valid), max_len, 40))], y_valid),\r\n                    batch_size=32, epochs=2, verbose=1)\r\n```\r\n\r\nTo clarify, X1_train is a list of tokenized sentences and X2_train is a list of hand-picked features for every token in every sentence. \r\n\r\n\r\nThe error that I'm getting when calling model.fit is the following one:\r\n\r\n```\r\n---------------------------------------------------------------------------\r\nAttributeError                            Traceback (most recent call last)\r\n<ipython-input-14-04a3722fa4b2> in <module>\r\n     51                     y_train,\r\n     52                     validation_data=([np.array(X1_valid), np.array(X2_valid).reshape((len(X2_valid), max_len, 40))], y_valid),\r\n---> 53                     batch_size=32, epochs=2, verbose=1)\r\n     54 hist = pd.DataFrame(history.history)\r\n\r\n/opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)\r\n   1098                 _r=1):\r\n   1099               callbacks.on_train_batch_begin(step)\r\n-> 1100               tmp_logs = self.train_function(iterator)\r\n   1101               if data_handler.should_sync:\r\n   1102                 context.async_wait()\r\n\r\n/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)\r\n    826     tracing_count = self.experimental_get_tracing_count()\r\n    827     with trace.Trace(self._name) as tm:\r\n--> 828       result = self._call(*args, **kwds)\r\n    829       compiler = \"xla\" if self._experimental_compile else \"nonXla\"\r\n    830       new_tracing_count = self.experimental_get_tracing_count()\r\n\r\n/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)\r\n    869       # This is the first call of __call__, so we have to initialize.\r\n    870       initializers = []\r\n--> 871       self._initialize(args, kwds, add_initializers_to=initializers)\r\n    872     finally:\r\n    873       # At this point we know that the initialization is complete (or less\r\n\r\n/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)\r\n    724     self._concrete_stateful_fn = (\r\n    725         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\r\n--> 726             *args, **kwds))\r\n    727 \r\n    728     def invalid_creator_scope(*unused_args, **unused_kwds):\r\n\r\n/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)\r\n   2967       args, kwargs = None, None\r\n   2968     with self._lock:\r\n-> 2969       graph_function, _ = self._maybe_define_function(args, kwargs)\r\n   2970     return graph_function\r\n   2971 \r\n\r\n/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)\r\n   3359 \r\n   3360           self._function_cache.missed.add(call_context_key)\r\n-> 3361           graph_function = self._create_graph_function(args, kwargs)\r\n   3362           self._function_cache.primary[cache_key] = graph_function\r\n   3363 \r\n\r\n/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)\r\n   3204             arg_names=arg_names,\r\n   3205             override_flat_arg_shapes=override_flat_arg_shapes,\r\n-> 3206             capture_by_value=self._capture_by_value),\r\n   3207         self._function_attributes,\r\n   3208         function_spec=self.function_spec,\r\n\r\n/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)\r\n    988         _, original_func = tf_decorator.unwrap(python_func)\r\n    989 \r\n--> 990       func_outputs = python_func(*func_args, **func_kwargs)\r\n    991 \r\n    992       # invariant: `func_outputs` contains only Tensors, CompositeTensors,\r\n\r\n/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)\r\n    632             xla_context.Exit()\r\n    633         else:\r\n--> 634           out = weak_wrapped_fn().__wrapped__(*args, **kwds)\r\n    635         return out\r\n    636 \r\n\r\n/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)\r\n    975           except Exception as e:  # pylint:disable=broad-except\r\n    976             if hasattr(e, \"ag_error_metadata\"):\r\n--> 977               raise e.ag_error_metadata.to_exception(e)\r\n    978             else:\r\n    979               raise\r\n\r\nAttributeError: in user code:\r\n\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:805 train_function  *\r\n        return step_function(self, iterator)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:795 step_function  **\r\n        outputs = model.distribute_strategy.run(run_step, args=(data,))\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:1259 run\r\n        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2730 call_for_each_replica\r\n        return self._call_for_each_replica(fn, args, kwargs)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:3417 _call_for_each_replica\r\n        return fn(*args, **kwargs)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:788 run_step  **\r\n        outputs = model.train_step(data)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:754 train_step\r\n        y_pred = self(x, training=True)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:1012 __call__\r\n        outputs = call_fn(inputs, *args, **kwargs)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py:425 call\r\n        inputs, training=training, mask=mask)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/functional.py:560 _run_internal_graph\r\n        outputs = node.layer(*args, **kwargs)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py:1012 __call__\r\n        outputs = call_fn(inputs, *args, **kwargs)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/keras/layers/core.py:917 call\r\n        result = self.function(inputs, **kwargs)\r\n    <ipython-input-7-21ffba0b5a13>:7 ElmoEmbedding\r\n        return elmo_model.signatures[\"tokens\"](tokens = tf.squeeze(tf.cast(x, tf.string)), sequence_len = tf.constant(batch_size * [max_len]))[\"elmo\"]\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py:1669 __call__\r\n        return self._call_impl(args, kwargs)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/wrap_function.py:247 _call_impl\r\n        args, kwargs, cancellation_manager)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py:1687 _call_impl\r\n        return self._call_with_flat_signature(args, kwargs, cancellation_manager)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py:1736 _call_with_flat_signature\r\n        return self._call_flat(args, self.captured_inputs, cancellation_manager)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py:1924 _call_flat\r\n        forward_function, args_with_tangents = forward_backward.forward()\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py:1448 forward\r\n        self._inference_args, self._input_tangents)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py:1207 forward\r\n        self._forward_and_backward_functions(inference_args, input_tangents))\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py:1407 _forward_and_backward_functions\r\n        outputs, inference_args, input_tangents)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py:910 _build_functions_for_outputs\r\n        src_graph=self._func_graph)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/gradients_util.py:552 _GradientsHelper\r\n        to_ops, from_ops, colocate_gradients_with_ops, func_graphs, xs_set)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/gradients_util.py:125 _PendingCount\r\n        between_op_list, between_ops, colocate_gradients_with_ops)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_state.py:780 MaybeCreateControlFlowState\r\n        loop_state.AddWhileContext(op, between_op_list, between_ops)\r\n    /opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/control_flow_state.py:577 AddWhileContext\r\n        outer_forward_ctxt = forward_ctxt.outer_context\r\n\r\n    AttributeError: 'NoneType' object has no attribute 'outer_context'\r\n```\r\n\r\nAny tips would help!", "comments": ["@popkristina \r\nIn order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),Thanks!", "> @popkristina In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),Thanks!\r\n\r\nI will reopen the issue as 'other'. It is not a standard bug. You can close this one, sorry.", "@popkristina Thank you for the update!\r\nAs per the above  [comment](https://github.com/tensorflow/tensorflow/issues/53575#issuecomment-1002723943) , closing this issue and we will track the other ticket #53579 . Thanks!\r\n\r\n> I will reopen the issue as 'other'. It is not a standard bug. You can close this one, sorry.", "Are you satisfied with the resolution of your issue?\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53575\">Yes</a>\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53575\">No</a>\n"]}, {"number": 53573, "title": "fixed some typos in the security markdown", "body": null, "comments": ["Hi @mihaimaruseac and @gbaned , the merging is blocked due to something went wrong with the CI checks(MacOS CPU Python3? ), but I couldn't see the details. Are there anything I can do to make it work? Thanks!", "Hi. Don't worry about the MacOS build here, it's currently failing at HEAD"]}, {"number": 53571, "title": "AveragePooling1D wrongly accept stride parameter to be None", "body": "**System information**\r\n- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes\r\n- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04\r\n- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A\r\n- TensorFlow installed from (source or binary): binary\r\n- TensorFlow version (use command below): 2.7.0\r\n- Python version: 3.7\r\n- Bazel version (if compiling from source): N/A\r\n- GCC/Compiler version (if compiling from source): N/A\r\n- CUDA/cuDNN version: 11.3/8\r\n- GPU model and memory: N/A\r\n\r\n**Describe the current behavior**\r\n`tf.keras.layers.AveragePooling1D` can output normal value when setting `stride` parameter to `None` with no warning/exceptions. In contrast `tf.keras.layers.Conv1D` will raise an exception to forbit such usage.\r\n\r\n**Describe the expected behavior**\r\nThis API should throw an exception or raise a warning instead of outputing a normal value.\r\n\r\n**[Contributing](https://www.tensorflow.org/community/contribute)**\r\n\r\n- Do you want to contribute a PR? (yes/no): yes\r\n- Briefly describe your candidate solution(if contributing): I haven't tried a solution yet and I am not familiar with your coding style to deal with such an issue.\r\n\r\n**Standalone code to reproduce the issue**\r\n```\r\nimport tensorflow as tf\r\nimport numpy as np\r\nx = tf.keras.layers.Input((32,3))\r\nlayer = tf.keras.layers.AveragePooling1D(pool_size=3, strides=None)\r\ny = layer(x)\r\nmodel = tf.keras.Model(x,y)\r\nmodel.predict(np.random.rand(10,32,3))\r\n```\r\nYou may access the code here:\r\nhttps://colab.research.google.com/drive/1u80B4LFEEctS5GOZj3GUd_G6u_3A9kcu?usp=sharing\r\n", "comments": ["Hi @maybeLee ! According to this [document](https://www.tensorflow.org/api_docs/python/tf/keras/layers/AveragePooling2D#args), When you are declaring Strides as **None** in AveragePooling1D, It is taking **strides size equal to pooling_size** But in case of [Conv1D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv1D#args) , Strides has to be an integer or tuple/list of a single integer, specifying the stride length of the convolution.", "Hi mohantym, thanks for your prompt reply. So this is the expected behavior. I will close the issue.", "Are you satisfied with the resolution of your issue?\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53571\">Yes</a>\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53571\">No</a>\n"]}, {"number": 53570, "title": "r2.8 cherry-pick request: Disable caching for ACL softmax primitives", "body": "This patch enables the use of ACL softmax primitives in oneDNN, and disables caching of these primitives when used in TensorFlow.\r\n\r\n@LukeIreland1 @nSircombe Could you please provide example performance improvement numbers this patch provides? Thank you!", "comments": ["Hi @penpornk, thanks for raising the cherry-pick request, and thanks @mihaimaruseac for taking a look and approving it.\r\n\r\n> please provide example performance improvement numbers...\r\n\r\nThe performance improvement from being able to use the the Compute Library based softmax primitive over the C++ reference implementation in oneDNN is sensitive to the problem size and thread count. The uplift can be as high as 5x, however there are cases (lower threads, smaller problem sizes etc.) where the reference implementation is preferable. In oneDNN there is a heuristic which will determine the final kernel selection (see https://github.com/oneapi-src/oneDNN/blob/aed66b1d9c5467a3a41dfb95321ef1b48d542e04/src/cpu/aarch64/acl_softmax.hpp#L135, https://github.com/oneapi-src/oneDNN/blob/aed66b1d9c5467a3a41dfb95321ef1b48d542e04/src/cpu/aarch64/acl_softmax.hpp#L163)", "Thank you very much for the detailed explanation, @nSircombe! :)"]}, {"number": 53569, "title": "convert_variables_to_constants_v2 not supper fo embedding?", "body": "TensorFlow not supper frozen ConcreteFunction when I convert My deepFM model,\r\n It's because convert_variables_to_constants_v2 not supper enbedding, I want to know the fix of this issue please?\r\n![image](https://user-images.githubusercontent.com/22836006/147644669-d550ed28-0715-495a-86b4-8b0b4b6d28c6.png)\r\n\r\n\r\n<em>Please make sure that this is a bug. As per our\r\n[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),\r\nwe only address code/doc bugs, performance issues, feature requests and\r\nbuild/installation issues on GitHub. tag:bug_template</em>\r\n\r\n**System information**\r\n- TensorFlow installed from (source or binary): pip\r\n- TensorFlow version (use command below): 2.3.4-gpu\r\n- Python version: 3.7\r\n- CUDA/cuDNN version: 10.1\r\n- GPU model and memory:  16G\r\n\r\n**Describe the current behavior**\r\nTensorFlow not supper frozen ConcreteFunction when I convert My deepFM model,\r\n It's because convert_variables_to_constants_v2 not supper enbedding\r\n\r\n**Describe the expected behavior**\r\nConver saved model to froze graph success\r\n\r\n**[Contributing](https://www.tensorflow.org/community/contribute)**\r\n\r\n- Do you want to contribute a PR? (yes/no):\r\n- Briefly describe your candidate solution(if contributing):\r\n\r\n**Standalone code to reproduce the issue**\r\n\r\n\r\n**Other info / logs** Include any logs or source code that would be helpful to\r\n", "comments": ["@GuoGuiRong \r\nIn order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),\r\nThanks!", "> @GuoGuiRong In order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose), Thanks!\r\n\r\nok\r\n", "@GuoGuiRong Thank you for the update!\r\nWe see that you're using older version of `TF 2.3.4`,  could you please try to upgrade to latest stable TF version` 2.7.0` and let us know the outcome?Thanks!", "I have fix it use Tensorflow 2.5.0 GPU, this is beasuce my model has some input that not used, A redundant input Cause it conver failed in TensorFlow2.3.0 GPU, I have remove this input and use Tensorflow 2.5.0 success.\r\nSo I close this issue, Thanks", "Are you satisfied with the resolution of your issue?\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53569\">Yes</a>\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53569\">No</a>\n"]}, {"number": 53568, "title": "GPU sync failed and CUDA_ERROR_ILLEGAL_ADDRESS error", "body": "**System information**\r\n- Have I written custom code: **yes**\r\n- OS Platform and Distribution: **ubuntu 20.04**\r\n- Mobile device if the issue happens on mobile device: **No**\r\n- TensorFlow installed from (source or binary): **binary**\r\n- TensorFlow version: **Tensorflow-1.4.0**\r\n- Python version: **Python 3.5.2**\r\n- Bazel version (if compiling from source):\r\n- GCC/Compiler version (if compiling from source):\r\n- CUDA/cuDNN version: **CUDA Version 8.0.61, cuDNN 7.0.5**\r\n- GPU model and memory: **GeForce GTX 1080 Ti with 11G memory**\r\n\r\n**Describe the current behavior**\r\nThe baseline model is implemented under TensorFlow 1.4.0, so I built my model based on this model. Then I made a docker and ran it in docker. When I train my model, it occasionally shows this error: \r\n`tensorflow.python.framework.errors_impl.InternalError: GPU sync failed`\r\nand\r\n`2017-11-08 12:24:52.838106: E tensorflow/stream_executor/cuda/cuda_timer.cc:59] Internal: error destroying CUDA event in context 0x51f18f0: CUDA_ERROR_ILLEGAL_ADDRESS`\r\n\r\n\r\nWhen using fewer training samples, it seems that there is no problem when training the model once (epoch=1). This problem usually occurs when I train the model 5 times (epoch=5).\r\nWhen more training samples are used, even if the model is only trained once, this problem will occur more frequently.\r\n\r\nI downloaded cudnn7.0.5 according to the [this](https://github.com/tensorflow/tensorflow/issues/14363), but it did not alleviate this problem.\r\nI had tried to restart the docker but it didn't help.\r\nThe GPU memory is not exceeded. In the case of successful training, it only takes up 30% of the memory.\r\n\r\nAt the same time, I found the following error in the system log. (by `sudo journalctl -f`)\r\n`Dec 29 15:02:52 zpp-lab kernel: NVRM: Xid (PCI:0000:17:00): 31, pid=1342831, Ch 00000012, intr 30000000. MMU Fault: ENGINE GRAPHICS GPCCLIENT_T1_9 faulted @ 0x7f96_54002000. Fault is of type FAULT_PDE ACCESS_TYPE_ATOMIC\r\n`\r\n\r\nThen I run my code with cuda-memcheck, [here](https://www.dropbox.com/s/9zdegkd64kzmtgk/cuda_memcheck.txt?dl=0) is the error info.\r\n\r\n\r\n**Describe the expected behavior**\r\n\r\n**[Contributing](https://www.tensorflow.org/community/contribute)**\r\n\r\n- Do you want to contribute a PR? (yes/no): no\r\n- Briefly describe your candidate solution(if contributing):\r\n\r\n**Standalone code to reproduce the issue**\r\nProvide a reproducible test case that is the bare minimum necessary to generate\r\nthe problem. If possible, please share a link to Colab/Jupyter/any notebook.\r\n[https://github.com/fakeppz/demo](https://github.com/fakeppz/demo)\r\n\r\n**Other info / logs** Include any logs or source code that would be helpful to\r\ndiagnose the problem. If including tracebacks, please include the full\r\ntraceback. Large logs and files should be attached.\r\n", "comments": ["@Jeaninezpp ,\r\nWe see that you are using tf version 1.4, 1.x is not actively supported, please update to latest stable v2.7 and let us know if you are using same issue.Please take a look at this link for tested build [configurations](https://www.tensorflow.org/install/source#gpu).Thanks", "This issue has been automatically marked as stale because it has no recent activity. It will be closed if no further activity occurs. Thank you.\n", "Are you satisfied with the resolution of your issue?\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53568\">Yes</a>\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53568\">No</a>\n"]}, {"number": 53567, "title": "TripletSemiHardLoss produces only NaNs when training with a TPU", "body": "This bug was discovered in Google Colab, but appears to be rooted in TripletSemiHardLoss.\r\n\r\nHere's an example Colab that illustrates the problem:\r\nhttps://colab.research.google.com/drive/10GuYAFDMuxXe2jqdj7hy_I7XcApJFmj7?usp=sharing\r\n\r\n- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):\r\n\r\nI combined the example Colab here:\r\nhttps://colab.research.google.com/github/GoogleCloudPlatform/training-data-analyst/blob/master/courses/fast-and-lean-data-science/01_MNIST_TPU_Keras.ipynb\r\n\r\nwith some of the steps here:\r\nhttps://www.tensorflow.org/addons/tutorials/losses_triplet\r\n\r\nSpecifically:\r\nI deleted the line: `label = tf.one_hot(label, 10)`\r\nI replaced the last layer of the network (Dense ReLU) with these two layers:\r\n```\r\n tf.keras.layers.Dense(10, activation=None),\r\n tf.keras.layers.Lambda(lambda x: tf.math.l2_normalize(x, axis=1)) # L2 normalize embeddings\r\n```\r\n\r\nAnd then changed the loss function in `make_model` to: `tfa.losses.TripletSemiHardLoss(distance_metric='angular', margin=0.2)`\r\n\r\nWhen run on a CPU or GPU, the training works as expected and the loss function produces reasonable results.\r\nWhen run on a TPU, the training runs (as in it does not produce an error), but the loss function produces only NaN, causing the training to effectively fail.\r\n\r\nI understand that not all operations are available on TPUs and TripletSemiHardLoss may fundamentally not work on a TPU, but it should at least fail with an informative error message.", "comments": ["@kbelenky \r\nPlease post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)\r\nTo know more see;\r\n[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)\r\nThank you!", "This issue has been automatically marked as stale because it has no recent activity. It will be closed if no further activity occurs. Thank you.\n", "Closing as stale. Please reopen if you'd like to work on this further.\n", "Are you satisfied with the resolution of your issue?\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53567\">Yes</a>\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53567\">No</a>\n"]}, {"number": 53565, "title": " No such package '@png_archive//': Traceback (most recent call last):", "body": "### 1. System information\r\nInstallation Package Version\uff1a\r\nCUDA 10.0\r\nCUDNN 7.6\r\nBazel  0.2\r\nmsys  X64\r\ntensorflow 1.13.1\r\n### 2. Code\r\n\r\nI get the following error when compiling TENSORFLOW\r\nF:/tensorflow-1.13.1/source/tensorflow/core/platform/default/build_config/BUILD:188:1: no such package '@png_archive//': Traceback (most recent call last):\r\n        File \"F:/tensorflow-1.13.1/source/third_party/repo.bzl\", line 106\r\n                _apply_patch(ctx, ctx.attr.patch_file)\r\n        File \"F:/tensorflow-1.13.1/source/third_party/repo.bzl\", line 73, in _apply_patch\r\n                _execute_and_check_ret_code(ctx, cmd)\r\n        File \"F:/tensorflow-1.13.1/source/third_party/repo.bzl\", line 52, in _execute_and_check_ret_code\r\n                fail(\"Non-zero return code({1}) when ...))\r\nNon-zero return code(127) when executing 'C:\\msys64\\usr\\bin\\bash.exe -l -c \"patch\" \"-p1\" \"-d\" \"C:/users/cgh/_bazel_llc/guutvuc2/external/png_archive\" \"-i\" \"F:/tensorflow-1.13.1/source/third_party/png_fix_rpi.patch\"':\r\nStdout:\r\nStderr: /usr/bin/bash: patch: \u93c8\ue045\u58d8\u9352\u677f\u61e1\u6d60? and referenced by '//tensorflow/core/platform/default/build_config:png'\r\n\r\nAny other info / logs\r\n\r\nERROR: Analysis of target '//tensorflow:libtensorflow_cc.so' failed; build aborted: Analysis failed\r\nINFO: Elapsed time: 29.908s\r\nINFO: 0 processes.\r\nFAILED: Build did NOT complete successfully (95 packages loaded, 4625 targets configured)\r\n    Fetching @icu; fetching 7s\r\n    Fetching @grpc; fetching\r\n    Fetching @png_archive; fetching\r\nWARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:\r\n", "comments": ["Hi @Dragonchengllc ! 1.x versions are supported anymore. Please refer this[ link](https://www.tensorflow.org/install/source) to build Tensorflow from source. Attaching relevant threads for reference. Ref [ 1 ](https://github.com/tensorflow/tensorflow/issues/27778) ,[2](https://github.com/tensorflow/tensorflow/issues/21880) . Thank you!", "This issue has been automatically marked as stale because it has no recent activity. It will be closed if no further activity occurs. Thank you.\n", "Closing as stale. Please reopen if you'd like to work on this further.\n", "Are you satisfied with the resolution of your issue?\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53565\">Yes</a>\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53565\">No</a>\n"]}, {"number": 53564, "title": "v.2.7: Failure to build for iOS", "body": "When building our code for iOS against TensorFlow Lite 2.7.0, we're seeing the following errors:\r\n\r\n```\r\nIn file included from /Users/alex/.conan/data/ooo/1.0/ci/local/source/integrations/tflite/TFLiteStage.cpp:37:\r\nIn file included from /Users/alex/.conan/data/tensorflow-lite/2.7.0.11+fb1696d4/ci/branch_release_2.7/package/3b95326f653baf403ae4d70dae74814d9c4fef8a/lib/TensorFlowLiteCMetal.framework/Headers/TensorFlowLiteCMetal.h:1:\r\nIn file included from /Users/alex/.conan/data/tensorflow-lite/2.7.0.11+fb1696d4/ci/branch_release_2.7/package/3b95326f653baf403ae4d70dae74814d9c4fef8a/lib/TensorFlowLiteCMetal.framework/Headers/metal_delegate.h:19:\r\nIn file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Metal.framework/Headers/Metal.h:9:\r\nIn file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Metal.framework/Headers/MTLTypes.h:8:\r\nIn file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:8:\r\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:523:1: error: expected unqualified-id\r\n@class NSString, Protocol;\r\n^\r\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:525:9: error: unknown type name 'NSString'\r\ntypedef NSString * NSExceptionName NS_TYPED_EXTENSIBLE_ENUM;\r\n        ^\r\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:526:9: error: unknown type name 'NSString'\r\ntypedef NSString * NSRunLoopMode NS_TYPED_EXTENSIBLE_ENUM;\r\n        ^\r\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:528:19: error: unknown type name 'NSString'\r\nFOUNDATION_EXPORT NSString *NSStringFromSelector(SEL aSelector);\r\n                  ^\r\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:529:44: error: unknown type name 'NSString'\r\nFOUNDATION_EXPORT SEL NSSelectorFromString(NSString *aSelectorName);\r\n                                           ^\r\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:531:19: error: unknown type name 'NSString'\r\nFOUNDATION_EXPORT NSString *NSStringFromClass(Class aClass);\r\n                  ^\r\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:532:53: error: unknown type name 'NSString'\r\nFOUNDATION_EXPORT Class _Nullable NSClassFromString(NSString *aClassName);\r\n                                                    ^\r\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:534:19: error: unknown type name 'NSString'\r\nFOUNDATION_EXPORT NSString *NSStringFromProtocol(Protocol *proto) API_AVAILABLE(macos(10.5), ios(2.0), watchos(2.0), tvos(9.0));\r\n                  ^\r\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:534:50: error: unknown type name 'Protocol'\r\nFOUNDATION_EXPORT NSString *NSStringFromProtocol(Protocol *proto) API_AVAILABLE(macos(10.5), ios(2.0), watchos(2.0), tvos(9.0));\r\n                                                 ^\r\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:535:19: error: unknown type name 'Protocol'\r\nFOUNDATION_EXPORT Protocol * _Nullable NSProtocolFromString(NSString *namestr) API_AVAILABLE(macos(10.5), ios(2.0), watchos(2.0), tvos(9.0));\r\n                  ^\r\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:535:61: error: unknown type name 'NSString'\r\nFOUNDATION_EXPORT Protocol * _Nullable NSProtocolFromString(NSString *namestr) API_AVAILABLE(macos(10.5), ios(2.0), watchos(2.0), tvos(9.0));\r\n                                                            ^\r\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:539:30: error: unknown type name 'NSString'\r\nFOUNDATION_EXPORT void NSLog(NSString *format, ...) NS_FORMAT_FUNCTION(1,2) NS_NO_TAIL_CALL;\r\n                             ^\r\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:539:53: error: format argument not an NSString\r\nFOUNDATION_EXPORT void NSLog(NSString *format, ...) NS_FORMAT_FUNCTION(1,2) NS_NO_TAIL_CALL;\r\n                             ~~~~~~~~~~~~~~~~       ^                  ~\r\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:94:49: note: expanded from macro 'NS_FORMAT_FUNCTION'\r\n        #define NS_FORMAT_FUNCTION(F,A) __attribute__((format(__NSString__, F, A)))\r\n                                                       ^                    ~\r\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:540:31: error: unknown type name 'NSString'\r\nFOUNDATION_EXPORT void NSLogv(NSString *format, va_list args) NS_FORMAT_FUNCTION(1,0) NS_NO_TAIL_CALL;\r\n                              ^\r\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:540:63: error: format argument not an NSString\r\nFOUNDATION_EXPORT void NSLogv(NSString *format, va_list args) NS_FORMAT_FUNCTION(1,0) NS_NO_TAIL_CALL;\r\n                              ~~~~~~~~~~~~~~~~                ^                  ~\r\n/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:94:49: note: expanded from macro 'NS_FORMAT_FUNCTION'\r\n        #define NS_FORMAT_FUNCTION(F,A) __attribute__((format(__NSString__, F, A)))\r\n```\r\n\r\nThe same exact code building in the same exact environment against TFLite 2.6.2 builds with no errors.\r\n", "comments": ["@w3sip \r\nIn order to expedite the trouble-shooting process here,Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),Thanks!", "in c33cc37d1c70, `import <Metal/Metal.h>` was added. The `Metal.h` provides Objective-C interface, so when compiling C++ code, you need to pass `-xobjective-c++` to clang to use Objective-C++ instead of pure C++ ", "@freedomtan - thanks, that's very helpful. Solved the problem.", "Are you satisfied with the resolution of your issue?\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53564\">Yes</a>\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53564\">No</a>\n"]}, {"number": 53562, "title": "rewording in markdown security file", "body": "clearer wording in the SECURITY.md file", "comments": []}, {"number": 53561, "title": "[PluggableDevice] Add DEVICE_DEFAULT registration for strided slice ops", "body": null, "comments": ["Hi,\r\n\r\nCould someone review this PR? This is something that we need for the release of our pluggable device plugin.\r\n\r\nThank you!"]}, {"number": 53560, "title": "Test change for running presubmits", "body": "DO NOT SUBMIT. I'm using this PR to run some tests related to presubmits.", "comments": []}, {"number": 53559, "title": "Fix flag value that was accidentally left off.", "body": "PiperOrigin-RevId: 417851286\r\nChange-Id: I78cb6c85a81dc27b81d8d521ae1b90fe562a7bd0\r\n(cherry picked from commit ed445770c3d91926b3a66997c605b47d3cec8ed0)", "comments": []}, {"number": 53558, "title": "Is it possible to build tensorflow lite C API to .hex file if the microcontroller such as AURIX TC29xT, which doesn't have any operating system ", "body": "<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>\r\n\r\n**System information**\r\n- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): None\r\n- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: AURIX TC29xT\r\n- TensorFlow installed from (source or binary): \r\n- TensorFlow version:\r\n- Python version:\r\n- Installed using virtualenv? pip? conda?:\r\n- Bazel version (if compiling from source):\r\n- GCC/Compiler version (if compiling from source):\r\n- CUDA/cuDNN version: \r\n- GPU model and memory:\r\n\r\n\r\n\r\n**Describe the problem**\r\n\r\n**Provide the exact sequence of commands / steps that you executed before running into the problem**\r\nEven if I understand we can build tensorflow lite C API into .so file for microcontroller with linux system, for the application of electrical control unit (ECU), is that possible to build C API into .hex file so as to use the library into the microcontroller without OS?\r\n\r\n**Any other info / logs**\r\nInclude any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.\r\n", "comments": ["Hi @lusiliang93 ! Could you check these threads for answer ? Ref [1](https://www.tensorflow.org/lite/microcontrollers), [2](https://towardsdatascience.com/tensorflow-on-arduino-b336f08fa0e9), [3](https://ss64.com/osx/xxd.html) .", "Thanks for the reference. Based on your references, I guess the model needs to be dumped into hex file. In addition, there is no need to build tensorflow lite api into .so in order to use tensorflow lite C API in such microcontroller. Am I right? ", "Yes @lusiliang93 ! You can use the lite model  after[ converting ](https://blog.tensorflow.org/2019/11/how-to-get-started-with-machine.html)into a  header file and importing it as a library . I found a thread from [Mouser electronics](https://www.mouser.com/applications/voice-assistant-tensorflow-lite/) confirming the same.  \r\n\r\n\r\n![image](https://user-images.githubusercontent.com/86464649/147633036-c7e74415-eb0f-4d68-9a21-d3230247a3b4.png)  \r\nPlease move this issue to closed status if it helped. Thank you!\r\n", "Many thanks for your answer. I have another question that if tensorflow lite for microcontrollers has C API since the compiler used currently can only compile C scripts. Thanks!", "@lusiliang93 ! TFlite library is based on C++ api. Please refer this [guide](https://www.tensorflow.org/lite/microcontrollers/library) to start with. Thank you!  ", "Thanks for your answer. A very naive question: If the compiler is C99 compliance only, how much effort will it take to make the microcontroller succeed in running tensorflow lite? Thanks!", "Hi @lusiliang93 ! Could you please post  on [Forum/](https://discuss.tensorflow.org/) [SO](https://stackoverflow.com/) about this as there will be larger community to address this issue ? Thanks!", "This issue has been automatically marked as stale because it has no recent activity. It will be closed if no further activity occurs. Thank you.\n", "Closing as stale. Please reopen if you'd like to work on this further.\n", "Are you satisfied with the resolution of your issue?\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53558\">Yes</a>\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53558\">No</a>\n"]}, {"number": 53557, "title": "Compile selected tflite from bazel failed.", "body": "<em>Please make sure that this is a bug. As per our\r\n[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),\r\nwe only address code/doc bugs, performance issues, feature requests and\r\nbuild/installation issues on GitHub. tag:bug_template</em>\r\n\r\n**System information**\r\n- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no\r\n- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux\r\n- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:\r\n- TensorFlow installed from (source or binary): source\r\n- TensorFlow version (use command below): 2.7.0\r\n- Python version: 3.6\r\n- Bazel version (if compiling from source): 4.4.0\r\n- GCC/Compiler version (if compiling from source): 5.2.0\r\n- CUDA/cuDNN version:\r\n- GPU model and memory:\r\n\r\n**Describe the current behavior**\r\nI followed the example here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/guide/reduce_binary_size.md to build a tflite library with selected tf ops.\r\nThe BUILD file is:\r\n```\r\nload(  \r\n    \"@org_tensorflow//tensorflow/lite/delegates/flex:build_def.bzl\",\r\n    \"tflite_flex_shared_library\"\r\n)         \r\n          \r\n# Shared lib target for convenience, pulls in the standard set of TensorFlow\r\n# ops and kernels. The output library name is platform dependent:\r\n#   - Linux/Android: `libtensorflowlite_flex.so`\r\n#   - Mac: `libtensorflowlite_flex.dylib`\r\n#   - Windows: `libtensorflowlite_flex.dll`\r\ntflite_flex_shared_library(\r\n  name = \"tensorflowlite_flex\",\r\n  models = [ \r\n      \":opennmt.tflite\",                                                                                                                                      \r\n  ],   \r\n)\r\n```\r\nHere is the build command:\r\n```\r\nbazel build -c opt --cxxopt='--std=c++14' \\\r\n      --config=monolithic \\\r\n      --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \\\r\n      //tmp2:tensorflowlite_flex\r\n```\r\nAnd here is the full log:\r\n```\r\nINFO: Options provided by the client:\r\n  Inherited 'common' options: --isatty=1 --terminal_columns=158\r\nINFO: Reading rc options for 'build' from /data/nmt3/tensorflow_src/.bazelrc:\r\n  Inherited 'common' options: --experimental_repo_remote_exec\r\nINFO: Reading rc options for 'build' from /data/nmt3/tensorflow_src/.bazelrc:\r\n  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/fallback,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils\r\nINFO: Found applicable config definition build:short_logs in file /data/nmt3/tensorflow_src/.bazelrc: --output_filter=DONT_MATCH_ANYTHING\r\nINFO: Found applicable config definition build:v2 in file /data/nmt3/tensorflow_src/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1\r\nINFO: Found applicable config definition build:monolithic in file /data/nmt3/tensorflow_src/.bazelrc: --define framework_shared_object=false\r\nINFO: Found applicable config definition build:linux in file /data/nmt3/tensorflow_src/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes\r\nINFO: Found applicable config definition build:dynamic_kernels in file /data/nmt3/tensorflow_src/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS\r\nWARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/c3e082762b7664bbc7ffd2c39e86464928e27c0c.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found\r\nWARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_swift/releases/download/0.21.0/rules_swift.0.21.0.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found\r\nWARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/rules_apple/releases/download/0.31.3/rules_apple.0.31.3.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found\r\nWARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/bazelbuild/apple_support/releases/download/0.10.0/apple_support.0.10.0.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found\r\nINFO: Build option --define has changed, discarding analysis cache.\r\nDEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = \"1596824487 -0400\"\r\nDEBUG: Repository io_bazel_rules_docker instantiated at:\r\n  /data/nmt3/tensorflow_src/WORKSPACE:23:14: in <toplevel>\r\n  /data/nmt3/tensorflow_src/tensorflow/workspace0.bzl:108:34: in workspace\r\n  /root/.cache/bazel/_bazel_root/dadf5c5bfc89a01814f2e47e8a82306e/external/bazel_toolchains/repositories/repositories.bzl:35:23: in repositories\r\nRepository rule git_repository defined at:\r\n  /root/.cache/bazel/_bazel_root/dadf5c5bfc89a01814f2e47e8a82306e/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>\r\nWARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/XNNPACK/archive/113092317754c7dea47bfb3cb49c4f59c3c1fa10.zip failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found\r\nWARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/oneapi-src/oneDNN/archive/v2.5-rc.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found\r\nINFO: Analyzed target //tmp2:tensorflowlite_flex (1 packages loaded, 18165 targets configured).\r\nINFO: Found 1 target...\r\nERROR: /data/nmt3/tensorflow_src/tensorflow/core/kernels/sparse/BUILD:32:18: Compiling tensorflow/core/kernels/sparse/mat_mul_op.cc failed: (Exit 1): gcc failed: error executing command /usr/local/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 215 argument(s) skipped)\r\ntensorflow/core/kernels/sparse/mat_mul_op.cc: In lambda function:\r\ntensorflow/core/kernels/sparse/mat_mul_op.cc:308:33: internal compiler error: in gimplify_var_or_parm_decl, at gimplify.c:1801\r\n           HandleBatchAndRowRange(\r\n                                 ^\r\n0x92054c gimplify_var_or_parm_decl\r\n        ../../gcc/gimplify.c:1801\r\n0x9243b3 gimplify_expr(tree_node**, gimple_statement_base**, gimple_statement_base**, bool (*)(tree_node*), int)\r\n        ../../gcc/gimplify.c:8485\r\n0x921953 gimplify_modify_expr\r\n        ../../gcc/gimplify.c:4644\r\n0x92310b gimplify_expr(tree_node**, gimple_statement_base**, gimple_statement_base**, bool (*)(tree_node*), int)\r\n        ../../gcc/gimplify.c:8054\r\n0x9258f6 gimplify_stmt(tree_node**, gimple_statement_base**)\r\n        ../../gcc/gimplify.c:5519\r\n0x925aaa gimplify_and_add(tree_node*, gimple_statement_base**)\r\n        ../../gcc/gimplify.c:423\r\n0x925aaa gimplify_init_ctor_eval\r\n        ../../gcc/gimplify.c:3662\r\n0x920ea6 gimplify_init_constructor\r\n        ../../gcc/gimplify.c:4017\r\n0x92179e gimplify_modify_expr_rhs\r\n        ../../gcc/gimplify.c:4274\r\n0x92187b gimplify_modify_expr\r\n        ../../gcc/gimplify.c:4603\r\n0x92310b gimplify_expr(tree_node**, gimple_statement_base**, gimple_statement_base**, bool (*)(tree_node*), int)\r\n        ../../gcc/gimplify.c:8054\r\n0x9258f6 gimplify_stmt(tree_node**, gimple_statement_base**)\r\n        ../../gcc/gimplify.c:5519\r\n0x9270a8 gimplify_and_add(tree_node*, gimple_statement_base**)\r\n        ../../gcc/gimplify.c:423\r\n0x9270a8 internal_get_tmp_var\r\n        ../../gcc/gimplify.c:568\r\n0x922f36 gimplify_expr(tree_node**, gimple_statement_base**, gimple_statement_base**, bool (*)(tree_node*), int)\r\n        ../../gcc/gimplify.c:8978\r\n0x9286a0 gimplify_call_expr\r\n        ../../gcc/gimplify.c:2477\r\n0x9243e7 gimplify_expr(tree_node**, gimple_statement_base**, gimple_statement_base**, bool (*)(tree_node*), int)\r\n        ../../gcc/gimplify.c:8025\r\n0x92492a gimplify_target_expr\r\n        ../../gcc/gimplify.c:5445\r\n0x92492a gimplify_expr(tree_node**, gimple_statement_base**, gimple_statement_base**, bool (*)(tree_node*), int)\r\n        ../../gcc/gimplify.c:8421\r\n0x923308 gimplify_addr_expr\r\n        ../../gcc/gimplify.c:4979\r\nPlease submit a full bug report,\r\nwith preprocessed source if appropriate.\r\nPlease include the complete backtrace with any bug report.\r\nSee <http://gcc.gnu.org/bugs.html> for instructions.\r\nTarget //tmp2:tensorflowlite_flex failed to build\r\nUse --verbose_failures to see the command lines of failed build steps.\r\nINFO: Elapsed time: 2829.962s, Critical Path: 291.83s\r\nINFO: 3978 processes: 100 internal, 3878 local.\r\nFAILED: Build did NOT complete successfully\r\n```\r\n**Describe the expected behavior**\r\n\r\n**[Contributing](https://www.tensorflow.org/community/contribute)**\r\n\r\n- Do you want to contribute a PR? (yes/no): no\r\n- Briefly describe your candidate solution(if contributing):\r\n\r\n**Standalone code to reproduce the issue**\r\nProvide a reproducible test case that is the bare minimum necessary to generate\r\nthe problem. If possible, please share a link to Colab/Jupyter/any notebook.\r\n\r\n**Other info / logs** Include any logs or source code that would be helpful to\r\ndiagnose the problem. If including tracebacks, please include the full\r\ntraceback. Large logs and files should be attached.\r\n", "comments": ["@SefaZeng Could you please check the [tested build configurations](https://www.tensorflow.org/install/source#tested_build_configurations) where it is recommended to use Python version `3.7-3.9` for TF v`2.7.0 `? Please let us know if it helps?Thank you!", "> @SefaZeng Could you please check the [tested build configurations](https://www.tensorflow.org/install/source#tested_build_configurations) where it is recommended to use Python version `3.7-3.9` for TF v`2.7.0 `? Please let us know if it helps?Thank you!\r\n\r\nThank you for your reply. I just found updating the gcc version solved this problem.  \r\nBTW, is there a example for how to use the shared library to inference the tflite model in c++? I found the example for static library but not for shared library. \r\nThx in advance!", "After update the gcc version, I can successfully build the libtensorflowlite.so with the changes mentioned in #52113 . I also want to build the select ops for my model. I change the tensorflow/lite/BUILD with dependency like this:\r\n```\r\ntflite_cc_shared_object(\r\n    name = \"tensorflowlite\",\r\n    # Until we have more granular symbol export for the C++ API on Windows,\r\n    # export all symbols.\r\n    features = [\"windows_export_all_symbols\"],\r\n    linkopts = select({\r\n        \"//tensorflow:macos\": [\r\n            \"-Wl,-exported_symbols_list,$(location //tensorflow/lite:tflite_exported_symbols.lds)\",\r\n        ],\r\n        \"//tensorflow:windows\": [],\r\n        \"//conditions:default\": [\r\n            \"-Wl,-z,defs\",\r\n            \"-Wl,--version-script,$(location //tensorflow/lite:tflite_version_script.lds)\",\r\n        ],\r\n    }),  \r\n    per_os_targets = True,\r\n    deps = [\r\n        \":framework\",\r\n        \":tflite_exported_symbols.lds\",\r\n        \":tflite_version_script.lds\",\r\n        #\"//tensorflow/lite/kernels:builtin_ops_all_linked\",\r\n        \"//tensorflow/lite/kernels:builtin_ops\",\r\n        \"//tensorflow/lite/delegates/flex:delegate\"                                                                                               \r\n    ],   \r\n)\r\n```\r\nAnd the build command is:\r\n`bazel build -c opt --cxxopt=--std=c++14 --config=monolithic //tensorflow/lite:libtensorflowlite.so`\r\nBut when I try to use this shared library libtensorflowlite.so, it raise errors like this:\r\n```\r\n[ 50%] Building CXX object CMakeFiles/nmt.dir/nmt.cpp.o\r\n[100%] Linking CXX executable nmt\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long) const@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::logic_error::logic_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::logic_error::logic_error(std::logic_error const&)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::range_error::range_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::length_error::length_error(char const*)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_of(char const*, unsigned long) const@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::out_of_range::out_of_range(char const*)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::resize(unsigned long, char)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `vtable for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_erase(unsigned long, unsigned long)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::logic_error::logic_error(char const*)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::overflow_error::overflow_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::_V2::error_category::default_error_condition(int) const@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy_chars(char*, char const*, char const*)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::_V2::error_category::equivalent(std::error_code const&, int) const@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::invalid_argument::invalid_argument(char const*)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::resize(unsigned long, wchar_t)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::out_of_range::out_of_range(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::push_back(char)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::_V2::error_category::equivalent(int, std::error_condition const&) const@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_not_of(char, unsigned long) const@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::runtime_error::runtime_error(char const*)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct(unsigned long, char)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::_V2::error_category::~error_category()@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::logic_error::logic_error(std::logic_error const&)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::runtime_error::runtime_error(std::runtime_error const&)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__atomic_futex_unsigned_base::_M_futex_notify_all(unsigned int*)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::overflow_error::overflow_error(char const*)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(unsigned long, unsigned long, char const*, unsigned long) const@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(unsigned long, unsigned long, char const*) const@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::range_error::range_error(char const*)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::runtime_error::runtime_error(std::runtime_error const&)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::domain_error::domain_error(char const*)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::length_error::length_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace_aux(unsigned long, unsigned long, unsigned long, char)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `typeinfo for std::_V2::error_category@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `operator delete[](void*, unsigned long)@CXXABI_1.3.9'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::operator>><char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `vtable for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::swap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::domain_error::domain_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_istringstream()@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::random_device::_M_init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `VTT for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()@GLIBCXX_3.4.26'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::logic_error::logic_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::underflow_error::underflow_error(char const*)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char const*, unsigned long) const@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::_V2::system_category()@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::_V2::error_category::_M_message[abi:cxx11](int) const@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(unsigned long, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::underflow_error::underflow_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::invalid_argument::invalid_argument(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `typeinfo for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose()@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::_V2::generic_category()@GLIBCXX_3.4.21'\r\n/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char, unsigned long) const@GLIBCXX_3.4.21'\r\ncollect2: error: ld returned 1 exit status\r\nmake[2]: *** [nmt] Error 1\r\nmake[1]: *** [CMakeFiles/nmt.dir/all] Error 2\r\nmake: *** [all] Error 2\r\n```\r\nAnd the CMakeLists.txt is:\r\n```\r\ncmake_minimum_required(VERSION 3.16)\r\nproject(nmt C CXX)\r\n \r\nADD_LIBRARY(tensorflowlite SHARED IMPORTED)\r\nset_property(TARGET tensorflowlite PROPERTY IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/lib/libtensorflowlite.so)\r\n \r\nINCLUDE_DIRECTORIES(\"/data/nmt3/tensorflow_src_2/tensorflow/lite\")\r\nINCLUDE_DIRECTORIES(\"/data/nmt3/tensorflow_src_2/tensorflow\")\r\nINCLUDE_DIRECTORIES(\"/data/nmt3/temp/external\")\r\n \r\nINCLUDE_DIRECTORIES(\"/data/nmt3/tensorflow_src_2\")\r\nINCLUDE_DIRECTORIES(\"/data/nmt3/tensorflow_src_2/bazel-bin\")\r\nINCLUDE_DIRECTORIES(\"/data/nmt3/tensorflow_src_2/bazel-out\")\r\nINCLUDE_DIRECTORIES(\"/data/nmt3/tensorflow_src_2/bazel-tensorflow_src_2\")\r\nINCLUDE_DIRECTORIES(\"/data/nmt3/flatbuffers/include\")\r\nINCLUDE_DIRECTORIES(\"/data/nmt3/temp\")\r\nINCLUDE_DIRECTORIES(\"/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite\")\r\n \r\nlink_directories(\"/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite\")                                                                         \r\nSET(CMAKE_CXX_FLAGS \"-std=c++11 -O3\")\r\nadd_executable(nmt nmt.cpp)\r\ntarget_link_libraries(nmt libtensorflowlite.so)\r\n```\r\nI can't find anything useful about this error. Any helps?", "> After update the gcc version, I can successfully build the libtensorflowlite.so with the changes mentioned in #52113 . I also want to build the select ops for my model. I change the tensorflow/lite/BUILD with dependency like this:\r\n> \r\n> ```\r\n> tflite_cc_shared_object(\r\n>     name = \"tensorflowlite\",\r\n>     # Until we have more granular symbol export for the C++ API on Windows,\r\n>     # export all symbols.\r\n>     features = [\"windows_export_all_symbols\"],\r\n>     linkopts = select({\r\n>         \"//tensorflow:macos\": [\r\n>             \"-Wl,-exported_symbols_list,$(location //tensorflow/lite:tflite_exported_symbols.lds)\",\r\n>         ],\r\n>         \"//tensorflow:windows\": [],\r\n>         \"//conditions:default\": [\r\n>             \"-Wl,-z,defs\",\r\n>             \"-Wl,--version-script,$(location //tensorflow/lite:tflite_version_script.lds)\",\r\n>         ],\r\n>     }),  \r\n>     per_os_targets = True,\r\n>     deps = [\r\n>         \":framework\",\r\n>         \":tflite_exported_symbols.lds\",\r\n>         \":tflite_version_script.lds\",\r\n>         #\"//tensorflow/lite/kernels:builtin_ops_all_linked\",\r\n>         \"//tensorflow/lite/kernels:builtin_ops\",\r\n>         \"//tensorflow/lite/delegates/flex:delegate\"                                                                                               \r\n>     ],   \r\n> )\r\n> ```\r\n> \r\n> And the build command is: `bazel build -c opt --cxxopt=--std=c++14 --config=monolithic //tensorflow/lite:libtensorflowlite.so` But when I try to use this shared library libtensorflowlite.so, it raise errors like this:\r\n> \r\n> ```\r\n> [ 50%] Building CXX object CMakeFiles/nmt.dir/nmt.cpp.o\r\n> [100%] Linking CXX executable nmt\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long) const@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::logic_error::logic_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::thread::_State::~_State()@GLIBCXX_3.4.22'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `__cxa_init_primary_exception@CXXABI_1.3.11'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::logic_error::logic_error(std::logic_error const&)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::range_error::range_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::length_error::length_error(char const*)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_of(char const*, unsigned long) const@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::out_of_range::out_of_range(char const*)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::resize(unsigned long, char)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `vtable for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_erase(unsigned long, unsigned long)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::logic_error::logic_error(char const*)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::overflow_error::overflow_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::_V2::error_category::default_error_condition(int) const@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_copy_chars(char*, char const*, char const*)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::_V2::error_category::equivalent(std::error_code const&, int) const@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::invalid_argument::invalid_argument(char const*)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::resize(unsigned long, wchar_t)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::out_of_range::out_of_range(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::_Ios_Openmode)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::push_back(char)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::_V2::error_category::equivalent(int, std::error_condition const&) const@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_not_of(char, unsigned long) const@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `typeinfo for std::thread::_State@GLIBCXX_3.4.22'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream()@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::runtime_error::runtime_error(char const*)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct(unsigned long, char)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::_V2::error_category::~error_category()@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::thread::_M_start_thread(std::unique_ptr<std::thread::_State, std::default_delete<std::thread::_State> >, void (*)())@GLIBCXX_3.4.22'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::assign(char const*)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::logic_error::logic_error(std::logic_error const&)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::runtime_error::runtime_error(std::runtime_error const&)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `vtable for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__atomic_futex_unsigned_base::_M_futex_notify_all(unsigned int*)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::overflow_error::overflow_error(char const*)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(unsigned long, unsigned long, char const*, unsigned long) const@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(unsigned long, unsigned long, char const*) const@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::range_error::range_error(char const*)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::runtime_error::runtime_error(std::runtime_error const&)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::domain_error::domain_error(char const*)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::length_error::length_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace_aux(unsigned long, unsigned long, unsigned long, char)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::getline<char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, char)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::append(char const*)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `typeinfo for std::_V2::error_category@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `operator delete[](void*, unsigned long)@CXXABI_1.3.9'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::operator>><char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_ostringstream()@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `vtable for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::str() const@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::swap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::domain_error::domain_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_istringstream()@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::random_device::_M_init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `VTT for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::basic_stringstream()@GLIBCXX_3.4.26'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::operator=(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::logic_error::logic_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__atomic_futex_unsigned_base::_M_futex_wait_until(unsigned int*, unsigned int, bool, std::chrono::duration<long, std::ratio<1l, 1l> >, std::chrono::duration<long, std::ratio<1l, 1000000000l> >)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::underflow_error::underflow_error(char const*)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char const*, unsigned long) const@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::_V2::system_category()@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::_V2::error_category::_M_message[abi:cxx11](int) const@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(unsigned long, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::underflow_error::underflow_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::invalid_argument::invalid_argument(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `typeinfo for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::runtime_error::runtime_error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_dispose()@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__exception_ptr::exception_ptr::exception_ptr(void*)@CXXABI_1.3.11'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::_V2::generic_category()@GLIBCXX_3.4.21'\r\n> /data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite/libtensorflowlite.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char, unsigned long) const@GLIBCXX_3.4.21'\r\n> collect2: error: ld returned 1 exit status\r\n> make[2]: *** [nmt] Error 1\r\n> make[1]: *** [CMakeFiles/nmt.dir/all] Error 2\r\n> make: *** [all] Error 2\r\n> ```\r\n> \r\n> And the CMakeLists.txt is:\r\n> \r\n> ```\r\n> cmake_minimum_required(VERSION 3.16)\r\n> project(nmt C CXX)\r\n>  \r\n> ADD_LIBRARY(tensorflowlite SHARED IMPORTED)\r\n> set_property(TARGET tensorflowlite PROPERTY IMPORTED_LOCATION ${CMAKE_CURRENT_SOURCE_DIR}/lib/libtensorflowlite.so)\r\n>  \r\n> INCLUDE_DIRECTORIES(\"/data/nmt3/tensorflow_src_2/tensorflow/lite\")\r\n> INCLUDE_DIRECTORIES(\"/data/nmt3/tensorflow_src_2/tensorflow\")\r\n> INCLUDE_DIRECTORIES(\"/data/nmt3/temp/external\")\r\n>  \r\n> INCLUDE_DIRECTORIES(\"/data/nmt3/tensorflow_src_2\")\r\n> INCLUDE_DIRECTORIES(\"/data/nmt3/tensorflow_src_2/bazel-bin\")\r\n> INCLUDE_DIRECTORIES(\"/data/nmt3/tensorflow_src_2/bazel-out\")\r\n> INCLUDE_DIRECTORIES(\"/data/nmt3/tensorflow_src_2/bazel-tensorflow_src_2\")\r\n> INCLUDE_DIRECTORIES(\"/data/nmt3/flatbuffers/include\")\r\n> INCLUDE_DIRECTORIES(\"/data/nmt3/temp\")\r\n> INCLUDE_DIRECTORIES(\"/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite\")\r\n>  \r\n> link_directories(\"/data/nmt3/tensorflow_src_2/bazel-bin/tensorflow/lite\")                                                                         \r\n> SET(CMAKE_CXX_FLAGS \"-std=c++11 -O3\")\r\n> add_executable(nmt nmt.cpp)\r\n> target_link_libraries(nmt libtensorflowlite.so)\r\n> ```\r\n> \r\n> I can't find anything useful about this error. Any helps?\r\n\r\nThis is mainly caused by the confusion of my local GCC environment, which has multiple versions of GCC. Now I can run the demo codes, but all the returned result is 0. Still debugging.", "Are you satisfied with the resolution of your issue?\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53557\">Yes</a>\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53557\">No</a>\n"]}, {"number": 53556, "title": "tf.data.experimental.save not saving my created tf.data.Dataset ", "body": "Tensorflow version: 2.7.0\r\n\r\n**Description of the issue:**\r\n\r\ni made use of the tf.data.experimental.CsvDataset class to create tf.data.Dataset from my csv data which i want to save with tf.data.experimental.save. upon attempting to save the dataset, the tf.data.experimental.save keeps running endlessly without saving the data. \r\n\r\n`csv data file size: 67108864 bytes`\r\n\r\n**Description of the expected behavior:**\r\ntf.data.experimental.save should save the tf.data.Dataset created to a file\r\n\r\n**Code to create the tf.data.Dataset and save same to file:**\r\n```\r\nDataset = tf.data.experimental.CsvDataset(\r\n    my_data.csv', \r\n    record_defaults=column_types, \r\n    header=True) # this runs successfully\r\n```\r\n\r\n`tf.data.experimental.save(Dataset, \"./Dataset\", compression='GZIP')` # this runs endlessly without throwing an error nor saving the dataset  to file\r\n\r\n\r\n\r\n\r\n\r\n\r\n", "comments": ["@Jaydeemourg ,\r\nIn order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.", "@tilakrayal thanks for your response. i have been able to save the dataset object. \r\n\r\nAnother question: Are the `tf.data.experimental.CsvDataset` available [Methods](https://www.tensorflow.org/api_docs/python/tf/data/experimental/CsvDataset#methods_2) enough to perform data wrangling and transformation usually done using libraries like scipy, numpy and pandas? . for example, i have been trying to perform an equivalent of the below line of pandas code using dataset methods but couldn't find the suitable one for it.   Looking forward to your reply.\r\n\r\n```\r\nsum_of_features = {}\r\nfor col in features:\r\n    sum_of_features[col] = sum_ofs[col].groupby([\"year\", \"month\", \"day\", \"second\"]).sum(col)\r\n```\r\n", "@Jaydeemourg ,\r\nKindly open a tf discussion forum issue for this as it is not a bug or feature request. There is a big community to support and learn from your questions.Thanks!", "@tilakrayal Done. Thanks!!! i am closing this issue", "Are you satisfied with the resolution of your issue?\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53556\">Yes</a>\n<a href=\"https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=https://github.com/tensorflow/tensorflow/issues/53556\">No</a>\n", "issue solved"]}]